In [1]:
import gym
import random
import numpy as np
import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression
from statistics import mean, median
from collections import Counter

curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [2]:
lr = 1e-4
env = gym.make('CartPole-v0')
env.reset()

[2018-01-22 17:28:14,371] Making new env: CartPole-v0


array([ 0.04125665,  0.02371672,  0.03806007,  0.03194964])

In [4]:
goal_steps = 500
score_requirement = 50
initial_games = 25000

In [ ]:
def some_random_games_first():
    for episode in range(5):
        env.reset()
        for t in range(goal_steps):
            env.render()
            # takes a random action from the action space
            action = env.action_space.sample()
            observation, reward, done, info = env.step(action)
            if done:
                break

In [ ]:
some_random_games_first()

In [5]:
# generate training samples
def initial_population():
    # stores the observations that a random move made
    training_data = []
    scores = []
    # appends the data only if the corresponding score happens to be above 50
    accepted_scores = []
    for i in range(initial_games):
        score = 0
        # store game memory as we will not know until the end of the game whether or not we beat the required score
        game_memory = []
        prev_observation = []
        # iterate through the plausible steps
        for j in range(goal_steps):
            action = random.randrange(0, 2) # generates a 0 or a 1
            observation, reward, done, info = env.step(action)
            
            if len(prev_observation) > 0:
                # basically looks at the previous frame and stores the current action and if the score is high enough,
                # it will be appended to the training data as we looked at the previous frame and did something on
                # this frame that increased our score, and we would like our neural network to learn this mapping
                game_memory.append([prev_observation, action])
                
            prev_observation = observation
            score += reward
            if done:
                break
        
        if score >= score_requirement:
            accepted_scores.append(score)
            # converting output into a one-hot vector for training
            for data in game_memory:
                if data[1] == 1:
                    output = [0, 1]
                elif data[1] == 0:
                    output = [1, 0]
                    
                # appends the observation and the given output(in one-hot vector format)
                training_data.append([data[0], output])
                
        env.reset()
        scores.append(score)
    
    training_data_save = np.array(training_data)
    np.save('cartpole-v0_training_data.npy', training_data_save)
    
    print('Average accepted score: ', mean(accepted_scores))
    print('Median accepted score: ', median(accepted_scores))
    print(Counter(accepted_scores))
    
    return training_data

In [11]:
initial_population()

[2018-01-22 12:41:14,917] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


Average accepted score:  60.79389312977099
Median accepted score:  57.0
Counter({51.0: 37, 54.0: 33, 50.0: 33, 52.0: 25, 55.0: 21, 56.0: 19, 60.0: 18, 57.0: 17, 53.0: 17, 62.0: 17, 59.0: 12, 67.0: 11, 58.0: 11, 65.0: 11, 61.0: 11, 70.0: 9, 63.0: 9, 71.0: 8, 64.0: 7, 69.0: 6, 77.0: 6, 78.0: 6, 74.0: 5, 68.0: 5, 76.0: 4, 66.0: 3, 93.0: 3, 75.0: 3, 90.0: 3, 73.0: 2, 89.0: 2, 83.0: 2, 85.0: 2, 81.0: 2, 84.0: 1, 118.0: 1, 109.0: 1, 80.0: 1, 79.0: 1, 91.0: 1, 94.0: 1, 110.0: 1, 92.0: 1, 88.0: 1, 87.0: 1, 86.0: 1, 98.0: 1})


[[array([-0.00597893, -0.20881766, -0.03947159,  0.2866333 ]), [0, 1]],
 [array([-0.01015528, -0.01315568, -0.03373893, -0.01823271]), [0, 1]],
 [array([-0.0104184 ,  0.18243348, -0.03410358, -0.32136684]), [1, 0]],
 [array([-0.00676973, -0.01218664, -0.04053092, -0.03963092]), [0, 1]],
 [array([-0.00701346,  0.18349238, -0.04132354, -0.34482122]), [0, 1]],
 [array([-0.00334361,  0.37917707, -0.04821996, -0.65024333]), [0, 1]],
 [array([ 0.00423993,  0.57493633, -0.06122483, -0.95771209]), [1, 0]],
 [array([ 0.01573865,  0.3806887 , -0.08037907, -0.68487543]), [1, 0]],
 [array([ 0.02335243,  0.18676928, -0.09407658, -0.41854145]), [0, 1]],
 [array([ 0.02708781,  0.38308966, -0.10244741, -0.73933759]), [1, 0]],
 [array([ 0.03474961,  0.18952029, -0.11723416, -0.48057278]), [1, 0]],
 [array([ 0.03854001, -0.00376857, -0.12684561, -0.22701755]), [1, 0]],
 [array([ 0.03846464, -0.19687106, -0.13138596,  0.02311639]), [1, 0]],
 [array([ 0.03452722, -0.38988803, -0.13092364,  0.27163005]), [

In [6]:
def neural_network_model(input_size):
    network = input_data(shape=[None, input_size, 1], name='input')
    network = fully_connected(network, 128, activation='relu')
    network = dropout(network, 0.8) # keep_rate=0.8
    network = fully_connected(network, 256, activation='relu')
    network = dropout(network, 0.8)
    network = fully_connected(network, 512, activation='relu')
    network = dropout(network, 0.8)
    network = fully_connected(network, 256, activation='relu')
    network = dropout(network, 0.8)
    network = fully_connected(network, 128, activation='relu')
    network = dropout(network, 0.8)
    network = fully_connected(network, 2, activation='softmax')
    network = regression(network, optimizer='adam', learning_rate=lr, loss='categorical_crossentropy', name='targets')
    model = tflearn.DNN(network, tensorboard_dir='log')
    return model

In [12]:
def train_model(training_data, model=False):
    X = np.array([i[0] for i in training_data]).reshape(-1, len(training_data[0][0]), 1) # grabs the observation column of the training data
    y = [i[1] for i in training_data]
    
    if not model:
        model = neural_network_model(input_size=len(X[0]))
    
    model.fit({'input':X}, {'targets':y}, n_epoch=3, snapshot_step=500, show_metric=True, run_id='cartpole-v0-v0.00')
    return model

In [13]:
training_data = initial_population()
model = train_model(training_data)

[2018-01-22 17:38:47,611] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


Average accepted score:  61.293577981651374
Median accepted score:  58.0
Counter({50.0: 77, 53.0: 75, 51.0: 63, 52.0: 55, 55.0: 50, 54.0: 50, 57.0: 33, 56.0: 31, 60.0: 31, 58.0: 29, 62.0: 28, 59.0: 27, 67.0: 27, 61.0: 26, 63.0: 25, 65.0: 20, 64.0: 19, 66.0: 18, 68.0: 17, 72.0: 14, 70.0: 11, 69.0: 11, 74.0: 10, 73.0: 9, 82.0: 9, 76.0: 9, 77.0: 8, 75.0: 8, 71.0: 7, 79.0: 6, 83.0: 6, 78.0: 6, 81.0: 5, 86.0: 5, 84.0: 5, 88.0: 5, 80.0: 4, 100.0: 3, 108.0: 2, 89.0: 2, 96.0: 2, 105.0: 2, 98.0: 2, 95.0: 2, 90.0: 2, 91.0: 2, 85.0: 2, 92.0: 1, 94.0: 1, 118.0: 1, 104.0: 1, 87.0: 1, 102.0: 1, 101.0: 1, 99.0: 1, 106.0: 1, 110.0: 1, 124.0: 1, 107.0: 1})
---------------------------------
Run id: cartpole-v0-v0.00
Log directory: log/
INFO:tensorflow:Summary name Accuracy/Adam_0 (raw) is illegal; using Accuracy/Adam_0__raw_ instead.


[2018-01-22 17:39:21,531] Summary name Accuracy/Adam_0 (raw) is illegal; using Accuracy/Adam_0__raw_ instead.


INFO:tensorflow:Summary name Accuracy_1/Adam_1 (raw) is illegal; using Accuracy_1/Adam_1__raw_ instead.


[2018-01-22 17:39:21,562] Summary name Accuracy_1/Adam_1 (raw) is illegal; using Accuracy_1/Adam_1__raw_ instead.


---------------------------------
Training samples: 105152
Validation samples: 0
--


InvalidArgumentError: You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,4,1]
	 [[Node: input_1/X = Placeholder[dtype=DT_FLOAT, shape=[?,4,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'input_1/X', defined at:
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-864639748772>", line 2, in <module>
    model = train_model(training_data)
  File "<ipython-input-12-537311490399>", line 6, in train_model
    model = neural_network_model(input_size=len(X[0]))
  File "<ipython-input-6-1e6ef326b56c>", line 2, in neural_network_model
    network = input_data(shape=[None, input_size, 1], name='input')
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tflearn\layers\core.py", line 81, in input_data
    placeholder = tf.placeholder(shape=shape, dtype=dtype, name="X")
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3090, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,4,1]
	 [[Node: input_1/X = Placeholder[dtype=DT_FLOAT, shape=[?,4,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [9]:
model.save('cartpole-v0-v0.10')

INFO:tensorflow:C:\Users\Aman Deep Singh\Documents\Python\Data Science\Machine Learning\Reinforcement Learning\cartpole-v0-v0.10 is not in all_model_checkpoint_paths. Manually adding it.


[2018-01-22 17:32:20,862] C:\Users\Aman Deep Singh\Documents\Python\Data Science\Machine Learning\Reinforcement Learning\cartpole-v0-v0.10 is not in all_model_checkpoint_paths. Manually adding it.


In [11]:
scores = []
choices = []
for each_game in range(100):
    score = 0
    game_memory = []
    prev_observation = []
    env.reset()
    for _ in range(goal_steps):
        # env.render()
        if len(prev_observation) == 0:
            action = random.randrange(0, 2)
        else:
            # print(model.predict(prev_observation.reshape(-1, len(prev_observation), 1)))
            action = np.argmax(model.predict(prev_observation.reshape(-1, len(prev_observation), 1))[0])
            
        choices.append(action)
        new_observation, reward, done, info = env.step(action)
        prev_observation = new_observation
        game_memory.append([new_observation, action])
        score += reward
        if done:
            break
    scores.append(score)
    
print('Average Score ', sum(scores)/len(scores))
print(f'Choice 1: {choices.count(1)/len(choices)}, Choice 0: {choices.count(0)/len(choices)}')

[[ 0.57397389  0.42602605]]
[[ 0.46915284  0.53084713]]
[[ 0.57493973  0.42506027]]
[[ 0.46986395  0.53013605]]
[[ 0.57662475  0.42337528]]
[[ 0.47124931  0.52875072]]
[[ 0.57901394  0.42098606]]
[[ 0.47333822  0.52666181]]
[[ 0.58216739  0.41783264]]
[[ 0.47611317  0.52388674]]
[[ 0.58607632  0.41392359]]
[[ 0.47961879  0.52038115]]
[[ 0.59081972  0.40918034]]
[[ 0.48393938  0.51606065]]
[[ 0.59647375  0.40352616]]
[[ 0.4891378   0.51086223]]
[[ 0.60316473  0.39683521]]
[[ 0.49543661  0.50456333]]
[[ 0.61101156  0.38898852]]
[[ 0.50322515  0.49677491]]
[[ 0.3988764   0.60112363]]
[[ 0.49604654  0.50395346]]
[[ 0.61045653  0.3895435 ]]
[[ 0.50325012  0.49674988]]
[[ 0.39869881  0.60130125]]
[[ 0.49566287  0.50433713]]
[[ 0.60897964  0.39102042]]
[[ 0.50229037  0.4977096 ]]
[[ 0.39759725  0.60240275]]
[[ 0.4944022   0.50559783]]
[[ 0.60663909  0.39336088]]
[[ 0.50039482  0.49960512]]
[[ 0.39567545  0.60432452]]
[[ 0.49222004  0.50777996]]
[[ 0.60334313  0.3966569 ]]
[[ 0.49762154  0.502

[[ 0.59062988  0.40937012]]
[[ 0.49193656  0.5080635 ]]
[[ 0.59163892  0.40836105]]
[[ 0.4938024   0.50619763]]
[[ 0.59308529  0.40691465]]
[[ 0.49606276  0.50393724]]
[[ 0.59496397  0.40503594]]
[[ 0.4987458   0.50125426]]
[[ 0.59726155  0.40273848]]
[[ 0.50187606  0.49812391]]
[[ 0.4074699   0.59253013]]
[[ 0.49169266  0.5083074 ]]
[[ 0.58827949  0.41172057]]
[[ 0.49288869  0.50711131]]
[[ 0.58885062  0.41114938]]
[[ 0.49433842  0.50566167]]
[[ 0.58974499  0.41025507]]
[[ 0.49595806  0.50404197]]
[[ 0.59095663  0.4090434 ]]
[[ 0.49784473  0.50215524]]
[[ 0.59250355  0.40749654]]
[[ 0.50006044  0.49993956]]
[[ 0.40762144  0.59237856]]
[[ 0.48976338  0.51023662]]
[[ 0.58190417  0.41809592]]
[[ 0.48990181  0.51009822]]
[[ 0.58129644  0.4187035 ]]
[[ 0.49013984  0.50986016]]
[[ 0.58080274  0.41919729]]
[[ 0.49046251  0.50953752]]
[[ 0.58037734  0.41962266]]
[[ 0.49085233  0.50914764]]
[[ 0.57997483  0.42002517]]
[[ 0.49130216  0.50869787]]
[[ 0.57962793  0.42037213]]
[[ 0.49179396  0.508

[[ 0.50290078  0.49709919]]
[[ 0.41617513  0.58382487]]
[[ 0.49577966  0.50422037]]
[[ 0.58364892  0.41635108]]
[[ 0.49907756  0.50092238]]
[[ 0.58480972  0.41519028]]
[[ 0.50292623  0.4970738 ]]
[[ 0.41851154  0.58148849]]
[[ 0.49549982  0.50450009]]
[[ 0.5778355   0.42216447]]
[[ 0.498106    0.50189394]]
[[ 0.57825094  0.42174911]]
[[ 0.50109524  0.49890476]]
[[ 0.4193078   0.58069217]]
[[ 0.4930847   0.50691527]]
[[ 0.5702967   0.42970333]]
[[ 0.49450034  0.50549966]]
[[ 0.56950659  0.43049341]]
[[ 0.49614906  0.503851  ]]
[[ 0.56874913  0.43125093]]
[[ 0.4980579  0.5019421]]
[[ 0.56806201  0.43193802]]
[[ 0.50024337  0.49975657]]
[[ 0.42403188  0.57596809]]
[[ 0.49207196  0.50792801]]
[[ 0.55947214  0.44052783]]
[[ 0.4925794   0.50742066]]
[[ 0.55718899  0.44281101]]
[[ 0.49312928  0.50687075]]
[[ 0.55472392  0.44527611]]
[[ 0.49371156  0.50628841]]
[[ 0.5519188   0.44808125]]
[[ 0.494178  0.505822]]
[[ 0.54894435  0.45105565]]
[[ 0.49463648  0.50536358]]
[[ 0.54577172  0.45422828]

[[ 0.49474442  0.50525558]]
[[ 0.53824103  0.46175891]]
[[ 0.48433617  0.51566386]]
[[ 0.53544933  0.4645507 ]]
[[ 0.47070462  0.52929538]]
[[ 0.5240919   0.47590807]]
[[ 0.45233771  0.5476622 ]]
[[ 0.50609857  0.49390137]]
[[ 0.43003643  0.56996351]]
[[ 0.48188588  0.51811409]]
[[ 0.54238772  0.45761222]]
[[ 0.46247768  0.53752232]]
[[ 0.52322221  0.47677785]]
[[ 0.43967426  0.56032568]]
[[ 0.49915507  0.50084496]]
[[ 0.56271684  0.43728316]]
[[ 0.48141322  0.5185867 ]]
[[ 0.54616493  0.45383507]]
[[ 0.46195567  0.53804439]]
[[ 0.52646756  0.47353241]]
[[ 0.4398154  0.5601846]]
[[ 0.50325394  0.49674603]]
[[ 0.41503114  0.58496886]]
[[ 0.47667852  0.52332151]]
[[ 0.54269248  0.45730758]]
[[ 0.45763555  0.54236442]]
[[ 0.52335513  0.47664487]]
[[ 0.43769717  0.56230283]]
[[ 0.50149566  0.49850431]]
[[ 0.41542113  0.58457893]]
[[ 0.47750819  0.52249181]]
[[ 0.54155606  0.45844394]]
[[ 0.46227345  0.53772658]]
[[ 0.5251801   0.47481996]]
[[ 0.44622445  0.55377549]]
[[ 0.50803798  0.49196

[[ 0.4677476   0.53225237]]
[[ 0.50407684  0.4959231 ]]
[[ 0.46990401  0.53009599]]
[[ 0.50429213  0.49570787]]
[[ 0.47237515  0.52762485]]
[[ 0.5046373  0.4953627]]
[[ 0.4751831   0.52481693]]
[[ 0.50520772  0.49479228]]
[[ 0.47824165  0.52175838]]
[[ 0.50541896  0.49458104]]
[[ 0.48160768  0.51839238]]
[[ 0.5051316   0.49486843]]
[[ 0.48477373  0.51522624]]
[[ 0.50440949  0.49559054]]
[[ 0.48766604  0.51233399]]
[[ 0.50327981  0.49672025]]
[[ 0.48979396  0.51020598]]
[[ 0.50195712  0.49804288]]
[[ 0.49135315  0.50864685]]
[[ 0.50094432  0.49905571]]
[[ 0.49222776  0.50777227]]
[[ 0.50009727  0.49990276]]
[[ 0.4925963   0.50740367]]
[[ 0.49944627  0.50055367]]
[[ 0.5072673   0.49273273]]
[[ 0.50155014  0.4984498 ]]
[[ 0.49368316  0.50631684]]
[[ 0.50114423  0.49885583]]
[[ 0.49398047  0.50601947]]
[[ 0.50099331  0.49900666]]
[[ 0.49445012  0.50554985]]
[[ 0.50079  0.49921]]
[[ 0.49511129  0.50488865]]
[[ 0.50051486  0.49948516]]
[[ 0.49591553  0.50408447]]
[[ 0.50024468  0.49975538]]


[[ 0.48956871  0.51043135]]
[[ 0.54032022  0.45967972]]
[[ 0.48846427  0.5115357 ]]
[[ 0.53644133  0.4635587 ]]
[[ 0.48706576  0.51293421]]
[[ 0.53222597  0.46777406]]
[[ 0.48548228  0.51451778]]
[[ 0.52788246  0.47211754]]
[[ 0.48384976  0.51615024]]
[[ 0.52343345  0.47656652]]
[[ 0.48220041  0.51779956]]
[[ 0.51896751  0.48103255]]
[[ 0.48045078  0.51954925]]
[[ 0.51448554  0.48551446]]
[[ 0.4792299   0.52077013]]
[[ 0.51000148  0.48999858]]
[[ 0.47920561  0.52079439]]
[[ 0.50561023  0.49438974]]
[[ 0.4792814   0.52071851]]
[[ 0.50115407  0.49884596]]
[[ 0.4790597  0.5209403]]
[[ 0.49683955  0.50316048]]
[[ 0.50877577  0.49122423]]
[[ 0.49413395  0.50586605]]
[[ 0.50499821  0.49500179]]
[[ 0.4924244   0.50757557]]
[[ 0.5017001   0.49829993]]
[[ 0.49173081  0.50826919]]
[[ 0.49900559  0.50099444]]
[[ 0.50627953  0.49372053]]
[[ 0.49717468  0.50282526]]
[[ 0.50396878  0.49603125]]
[[ 0.4959991   0.50400096]]
[[ 0.50229585  0.49770421]]
[[ 0.49541888  0.50458115]]
[[ 0.50110209  0.49889

[[ 0.5030244  0.4969756]]
[[ 0.41371188  0.58628809]]
[[ 0.49718162  0.50281835]]
[[ 0.57596642  0.42403349]]
[[ 0.50300217  0.49699792]]
[[ 0.41713211  0.58286792]]
[[ 0.49811321  0.50188684]]
[[ 0.57286251  0.42713743]]
[[ 0.50407761  0.49592239]]
[[ 0.42171207  0.5782879 ]]
[[ 0.49975833  0.5002417 ]]
[[ 0.57110077  0.4288992 ]]
[[ 0.50612682  0.49387321]]
[[ 0.42815188  0.57184821]]
[[ 0.50271463  0.49728534]]
[[ 0.42740905  0.57259095]]
[[ 0.4988353   0.50116462]]
[[ 0.56456709  0.43543291]]
[[ 0.50489724  0.49510273]]
[[ 0.43459311  0.56540692]]
[[ 0.50215006  0.49784985]]
[[ 0.43450749  0.56549251]]
[[ 0.49922767  0.5007723 ]]
[[ 0.55972356  0.44027644]]
[[ 0.50514942  0.49485061]]
[[ 0.44243503  0.55756497]]
[[ 0.50337136  0.49662864]]
[[ 0.44342822  0.55657172]]
[[ 0.50158858  0.49841136]]
[[ 0.4442319   0.55576807]]
[[ 0.49988768  0.5001123 ]]
[[ 0.55288953  0.44711044]]
[[ 0.50603461  0.49396539]]
[[ 0.45334491  0.54665506]]
[[ 0.50562549  0.49437454]]
[[ 0.4552955   0.54470

[[ 0.56083453  0.43916556]]
[[ 0.46076193  0.53923804]]
[[ 0.55828118  0.44171882]]
[[ 0.45868883  0.54131114]]
[[ 0.55530429  0.44469565]]
[[ 0.45622256  0.54377747]]
[[ 0.55185014  0.44814983]]
[[ 0.45331755  0.54668242]]
[[ 0.54805613  0.4519439 ]]
[[ 0.44992763  0.55007237]]
[[ 0.54371643  0.45628357]]
[[ 0.44595468  0.55404532]]
[[ 0.53867632  0.46132374]]
[[ 0.44126424  0.55873573]]
[[ 0.53286147  0.46713853]]
[[ 0.43571159  0.56428844]]
[[ 0.52606636  0.47393361]]
[[ 0.42919534  0.57080466]]
[[ 0.51825953  0.48174042]]
[[ 0.42161456  0.57838541]]
[[ 0.50956929  0.49043074]]
[[ 0.41258726  0.58741271]]
[[ 0.4996821   0.50031787]]
[[ 0.60178798  0.39821202]]
[[ 0.50183797  0.49816203]]
[[ 0.40606701  0.59393293]]
[[ 0.49165958  0.50834042]]
[[ 0.59029245  0.40970755]]
[[ 0.49298373  0.50701624]]
[[ 0.5903666   0.40963343]]
[[ 0.49504757  0.50495237]]
[[ 0.59116179  0.40883818]]
[[ 0.49789286  0.50210708]]
[[ 0.59269863  0.40730143]]
[[ 0.50122726  0.49877265]]
[[ 0.41102645  0.588

[[ 0.60297012  0.39702994]]
[[ 0.49821541  0.50178456]]
[[ 0.61105108  0.38894892]]
[[ 0.50594825  0.49405175]]
[[ 0.4015719   0.59842813]]
[[ 0.4992933   0.50070667]]
[[ 0.61217791  0.38782203]]
[[ 0.50719625  0.49280375]]
[[ 0.40288362  0.59711635]]
[[ 0.50067163  0.49932835]]
[[ 0.39614215  0.60385787]]
[[ 0.49308348  0.50691652]]
[[ 0.60373706  0.39626288]]
[[ 0.49914634  0.50085366]]
[[ 0.6120351   0.38796496]]
[[ 0.50714117  0.4928588 ]]
[[ 0.40289432  0.59710574]]
[[ 0.50072384  0.49927625]]
[[ 0.39625734  0.60374266]]
[[ 0.49324244  0.50675756]]
[[ 0.60390317  0.39609686]]
[[ 0.49941942  0.50058061]]
[[ 0.61232215  0.38767788]]
[[ 0.5075472   0.49245277]]
[[ 0.40337515  0.59662485]]
[[ 0.50126272  0.49873731]]
[[ 0.39688164  0.60311836]]
[[ 0.49392453  0.5060755 ]]
[[ 0.60465288  0.39534706]]
[[ 0.50028497  0.49971506]]
[[ 0.3958877   0.60411233]]
[[ 0.49292913  0.5070709 ]]
[[ 0.60354519  0.39645475]]
[[ 0.499212    0.50078797]]
[[ 0.61207795  0.38792205]]
[[ 0.50744206  0.492

[[ 0.59043443  0.40956557]]
[[ 0.48064137  0.51935863]]
[[ 0.59385842  0.40614155]]
[[ 0.48395354  0.51604646]]
[[ 0.59813172  0.40186834]]
[[ 0.48812643  0.5118736 ]]
[[ 0.60353708  0.39646286]]
[[ 0.49318045  0.50681961]]
[[ 0.61011136  0.38988867]]
[[ 0.49948218  0.50051785]]
[[ 0.61776477  0.38223523]]
[[ 0.5071137   0.49288625]]
[[ 0.40449384  0.59550625]]
[[ 0.49982846  0.50017148]]
[[ 0.61781955  0.38218042]]
[[ 0.50691891  0.493081  ]]
[[ 0.40394363  0.59605628]]
[[ 0.49904162  0.50095838]]
[[ 0.61663938  0.38336065]]
[[ 0.50554156  0.49445841]]
[[ 0.40231258  0.59768736]]
[[ 0.49709064  0.5029093 ]]
[[ 0.61414039  0.38585961]]
[[ 0.50291651  0.49708346]]
[[ 0.39950001  0.60049999]]
[[ 0.4938845  0.5061155]]
[[ 0.61007249  0.38992751]]
[[ 0.4988398  0.5011602]]
[[ 0.61618966  0.38381034]]
[[ 0.50511575  0.49488428]]
[[ 0.40192407  0.59807599]]
[[ 0.49641791  0.50358218]]
[[ 0.61314738  0.38685265]]
[[ 0.50197059  0.49802941]]
[[ 0.39862326  0.60137677]]
[[ 0.49269044  0.5073095

[[ 0.48827738  0.51172256]]
[[ 0.56212866  0.43787131]]
[[ 0.48682886  0.51317114]]
[[ 0.55978709  0.44021285]]
[[ 0.4850536  0.5149464]]
[[ 0.55712295  0.44287705]]
[[ 0.48294652  0.51705343]]
[[ 0.55409014  0.44590986]]
[[ 0.48039985  0.51960015]]
[[ 0.55066699  0.44933304]]
[[ 0.47737348  0.52262652]]
[[ 0.54671979  0.45328018]]
[[ 0.47383803  0.52616191]]
[[ 0.54215515  0.45784488]]
[[ 0.46968505  0.53031498]]
[[ 0.53683656  0.4631635 ]]
[[ 0.46479008  0.53520995]]
[[ 0.53082049  0.46917951]]
[[ 0.45898691  0.54101306]]
[[ 0.52396822  0.47603178]]
[[ 0.45233586  0.54766411]]
[[ 0.51610237  0.48389766]]
[[ 0.44497487  0.55502516]]
[[ 0.50685483  0.49314511]]
[[ 0.43826044  0.5617395 ]]
[[ 0.4963924   0.50360763]]
[[ 0.54155904  0.4584409 ]]
[[ 0.49358982  0.50641012]]
[[ 0.53465366  0.46534631]]
[[ 0.49072349  0.50927651]]
[[ 0.52784109  0.47215888]]
[[ 0.48816466  0.51183534]]
[[ 0.52147198  0.47852799]]
[[ 0.48607498  0.51392502]]
[[ 0.51557446  0.48442549]]
[[ 0.48445928  0.51554

[[ 0.5024783   0.49752176]]
[[ 0.39938369  0.60061634]]
[[ 0.49379149  0.5062086 ]]
[[ 0.60998887  0.39001113]]
[[ 0.49923873  0.50076127]]
[[ 0.61665481  0.38334516]]
[[ 0.50595814  0.49404186]]
[[ 0.40344694  0.59655303]]
[[ 0.49802157  0.5019784 ]]
[[ 0.61498952  0.38501057]]
[[ 0.50423634  0.49576372]]
[[ 0.40170673  0.5982933 ]]
[[ 0.49583319  0.50416684]]
[[ 0.6121521   0.38784793]]
[[ 0.50138938  0.49861071]]
[[ 0.39888579  0.60111421]]
[[ 0.49253425  0.50746572]]
[[ 0.60778886  0.39221114]]
[[ 0.4972322  0.5027678]]
[[ 0.61375123  0.3862488 ]]
[[ 0.50318766  0.4968124 ]]
[[ 0.40126577  0.59873426]]
[[ 0.49476287  0.5052371 ]]
[[ 0.61036098  0.38963899]]
[[ 0.499917    0.50008303]]
[[ 0.61648202  0.38351801]]
[[ 0.50633973  0.49366027]]
[[ 0.40492636  0.59507364]]
[[ 0.49840891  0.50159109]]
[[ 0.61429471  0.38570535]]
[[ 0.50413841  0.49586159]]
[[ 0.40260094  0.59739906]]
[[ 0.49564534  0.50435466]]
[[ 0.61052221  0.38947785]]
[[ 0.50059158  0.49940848]]
[[ 0.39884704  0.60115

[[ 0.49348259  0.50651741]]
[[ 0.55700684  0.44299316]]
[[ 0.47339714  0.5266028 ]]
[[ 0.53681338  0.46318656]]
[[ 0.44924685  0.55075312]]
[[ 0.5116877   0.48831233]]
[[ 0.42107537  0.5789246 ]]
[[ 0.48269355  0.51730645]]
[[ 0.55249584  0.44750422]]
[[ 0.45921573  0.54078424]]
[[ 0.52773321  0.47226679]]
[[ 0.43276384  0.56723613]]
[[ 0.50055838  0.49944162]]
[[ 0.403584  0.596416]]
[[ 0.46934626  0.53065372]]
[[ 0.54169494  0.45830503]]
[[ 0.44545245  0.55454755]]
[[ 0.51699072  0.48300925]]
[[ 0.41952348  0.58047646]]
[[ 0.48968378  0.51031625]]
[[ 0.56649935  0.43350062]]
[[ 0.47170919  0.52829081]]
[[ 0.54633141  0.45366868]]
[[ 0.45289338  0.54710656]]
[[ 0.52603257  0.47396737]]
[[ 0.4325102  0.5674898]]
[[ 0.50514507  0.49485496]]
[[ 0.41103956  0.58896041]]
[[ 0.48217312  0.51782686]]
[[ 0.55645704  0.44354299]]
[[ 0.46868312  0.53131694]]
[[ 0.54144961  0.45855039]]
[[ 0.45519742  0.54480261]]
[[ 0.52644169  0.47355834]]
[[ 0.44132593  0.5586741 ]]
[[ 0.51096338  0.48903665]

[[ 0.41153789  0.58846205]]
[[ 0.49308419  0.50691575]]
[[ 0.58470333  0.41529658]]
[[ 0.49395412  0.50604594]]
[[ 0.58483499  0.41516501]]
[[ 0.49503872  0.50496125]]
[[ 0.5850786  0.4149214]]
[[ 0.49634725  0.50365275]]
[[ 0.58534479  0.41465518]]
[[ 0.49785134  0.50214863]]
[[ 0.58583075  0.41416928]]
[[ 0.49945205  0.50054801]]
[[ 0.58654606  0.41345394]]
[[ 0.50129956  0.49870053]]
[[ 0.41309819  0.58690178]]
[[ 0.4911626  0.5088374]]
[[ 0.57657552  0.42342439]]
[[ 0.49089384  0.50910616]]
[[ 0.57526129  0.42473871]]
[[ 0.49064839  0.50935161]]
[[ 0.57397139  0.42602864]]
[[ 0.49040535  0.50959462]]
[[ 0.57267499  0.42732501]]
[[ 0.49009088  0.50990915]]
[[ 0.57128412  0.42871591]]
[[ 0.48967347  0.51032656]]
[[ 0.56977659  0.43022335]]
[[ 0.4890933   0.51090664]]
[[ 0.56813496  0.4318651 ]]
[[ 0.48833448  0.51166552]]
[[ 0.56631351  0.43368649]]
[[ 0.48737478  0.51262528]]
[[ 0.56431258  0.43568742]]
[[ 0.48618388  0.51381618]]
[[ 0.56207752  0.43792245]]
[[ 0.48469651  0.5153034

[[ 0.60526717  0.3947328 ]]
[[ 0.50386888  0.49613112]]
[[ 0.40064609  0.59935391]]
[[ 0.49719396  0.50280607]]
[[ 0.60521311  0.39478689]]
[[ 0.50427055  0.49572951]]
[[ 0.4012202  0.5987798]]
[[ 0.4977583   0.50224173]]
[[ 0.60548884  0.39451122]]
[[ 0.50503129  0.49496874]]
[[ 0.4021875   0.59781253]]
[[ 0.49874127  0.50125873]]
[[ 0.60620493  0.3937951 ]]
[[ 0.50627798  0.49372202]]
[[ 0.40369865  0.59630132]]
[[ 0.50029802  0.49970195]]
[[ 0.39725968  0.60274029]]
[[ 0.49309134  0.50690866]]
[[ 0.5982998   0.40170023]]
[[ 0.4993735  0.5006265]]
[[ 0.6063962  0.3936038]]
[[ 0.50735837  0.49264154]]
[[ 0.40524703  0.59475297]]
[[ 0.5019334   0.49806663]]
[[ 0.39937437  0.60062563]]
[[ 0.49530703  0.50469297]]
[[ 0.60011405  0.39988589]]
[[ 0.50226408  0.49773586]]
[[ 0.39993638  0.60006362]]
[[ 0.49594155  0.50405842]]
[[ 0.60053706  0.39946291]]
[[ 0.50318575  0.49681416]]
[[ 0.40115416  0.5988459 ]]
[[ 0.49723941  0.50276053]]
[[ 0.60163176  0.39836818]]
[[ 0.504848    0.49515197]

[[ 0.60248691  0.39751306]]
[[ 0.49567366  0.50432634]]
[[ 0.60536999  0.39463001]]
[[ 0.49873585  0.50126415]]
[[ 0.60898995  0.39101002]]
[[ 0.50245339  0.49754655]]
[[ 0.40234911  0.59765083]]
[[ 0.49233693  0.50766313]]
[[ 0.60092711  0.39907297]]
[[ 0.49452123  0.50547874]]
[[ 0.60346258  0.39653745]]
[[ 0.49726611  0.50273383]]
[[ 0.60668498  0.39331496]]
[[ 0.50061643  0.49938363]]
[[ 0.40048841  0.59951156]]
[[ 0.49009836  0.50990164]]
[[ 0.59761506  0.40238488]]
[[ 0.49179462  0.50820535]]
[[ 0.5995034   0.40049663]]
[[ 0.4939532   0.50604683]]
[[ 0.60200012  0.39799988]]
[[ 0.49663004  0.50336999]]
[[ 0.60513628  0.39486369]]
[[ 0.49988559  0.50011438]]
[[ 0.60893488  0.39106512]]
[[ 0.5037412   0.49625874]]
[[ 0.40451533  0.59548467]]
[[ 0.38148192  0.61851805]]
[[ 0.47046301  0.52953702]]
[[ 0.57602507  0.4239749 ]]
[[ 0.46602648  0.53397352]]
[[ 0.57029963  0.4297004 ]]
[[ 0.46200067  0.53799933]]
[[ 0.56468803  0.43531194]]
[[ 0.45808619  0.54191381]]
[[ 0.55918521  0.440

[[ 0.50026989  0.49973011]]
[[ 0.40968108  0.59031892]]
[[ 0.490159    0.50984097]]
[[ 0.57987434  0.42012572]]
[[ 0.49037996  0.50962007]]
[[ 0.5791533   0.42084673]]
[[ 0.49071643  0.50928354]]
[[ 0.57851553  0.42148453]]
[[ 0.49114463  0.50885546]]
[[ 0.57793397  0.42206603]]
[[ 0.49162421  0.50837582]]
[[ 0.57742226  0.4225778 ]]
[[ 0.49213448  0.50786549]]
[[ 0.57694113  0.42305887]]
[[ 0.4926796  0.5073204]]
[[ 0.57648897  0.42351103]]
[[ 0.49326     0.50673997]]
[[ 0.57605743  0.42394257]]
[[ 0.49383658  0.50616342]]
[[ 0.57561255  0.4243874 ]]
[[ 0.49440718  0.50559282]]
[[ 0.57518393  0.42481604]]
[[ 0.49489152  0.50510854]]
[[ 0.5747053   0.42529464]]
[[ 0.49533182  0.50466812]]
[[ 0.57419103  0.42580903]]
[[ 0.49573848  0.50426149]]
[[ 0.57360327  0.42639676]]
[[ 0.49606764  0.50393236]]
[[ 0.57293123  0.4270688 ]]
[[ 0.49634516  0.50365484]]
[[ 0.57215863  0.42784137]]
[[ 0.49653727  0.50346273]]
[[ 0.5712896  0.4287104]]
[[ 0.49665198  0.50334805]]
[[ 0.5702318  0.4297682]

[[ 0.60255086  0.39744911]]
[[ 0.50157404  0.49842599]]
[[ 0.40483427  0.59516573]]
[[ 0.491826  0.508174]]
[[ 0.59443581  0.40556422]]
[[ 0.49391365  0.50608635]]
[[ 0.59640676  0.40359324]]
[[ 0.49650726  0.50349283]]
[[ 0.59876454  0.40123546]]
[[ 0.49965757  0.50034237]]
[[ 0.601704    0.39829594]]
[[ 0.50338745  0.49661255]]
[[ 0.40791199  0.5920881 ]]
[[ 0.49372837  0.5062716 ]]
[[ 0.59401107  0.4059889 ]]
[[ 0.49581099  0.50418901]]
[[ 0.59568179  0.40431815]]
[[ 0.49835867  0.50164139]]
[[ 0.59786487  0.4021351 ]]
[[ 0.50139278  0.49860725]]
[[ 0.40652239  0.59347761]]
[[ 0.49109906  0.50890094]]
[[ 0.58853698  0.41146305]]
[[ 0.4922556   0.50774437]]
[[ 0.58904356  0.41095647]]
[[ 0.49371079  0.50628924]]
[[ 0.58990091  0.41009906]]
[[ 0.49543688  0.50456309]]
[[ 0.5911057  0.4088943]]
[[ 0.49736312  0.50263685]]
[[ 0.59267199  0.40732798]]
[[ 0.4996236   0.50037646]]
[[ 0.59458452  0.40541548]]
[[ 0.5022828   0.49771717]]
[[ 0.41007736  0.58992267]]
[[ 0.49238792  0.50761205]

[[ 0.46084794  0.53915209]]
[[ 0.5262869   0.47371307]]
[[ 0.44489807  0.55510193]]
[[ 0.50880647  0.49119353]]
[[ 0.42766246  0.57233763]]
[[ 0.49058074  0.50941926]]
[[ 0.54826939  0.45173064]]
[[ 0.48098674  0.51901323]]
[[ 0.53764445  0.46235555]]
[[ 0.47168821  0.52831179]]
[[ 0.5271194  0.4728806]]
[[ 0.46256906  0.53743094]]
[[ 0.51654977  0.48345026]]
[[ 0.45635569  0.54364431]]
[[ 0.50617462  0.49382544]]
[[ 0.45671287  0.54328716]]
[[ 0.49552748  0.50447255]]
[[ 0.51645517  0.48354486]]
[[ 0.49122036  0.5087797 ]]
[[ 0.50885534  0.49114466]]
[[ 0.48875162  0.51124835]]
[[ 0.50251073  0.49748924]]
[[ 0.48899019  0.51100981]]
[[ 0.49759358  0.50240636]]
[[ 0.50588167  0.4941183 ]]
[[ 0.49440905  0.50559092]]
[[ 0.6374647   0.36253527]]
[[ 0.5289036   0.47109637]]
[[ 0.42816314  0.57183689]]
[[ 0.52830559  0.47169438]]
[[ 0.42662585  0.57337415]]
[[ 0.52638024  0.47361973]]
[[ 0.42403045  0.57596964]]
[[ 0.52325761  0.4767423 ]]
[[ 0.42030439  0.57969558]]
[[ 0.51890421  0.48109

[[ 0.5043667   0.49563333]]
[[ 0.46057051  0.53942955]]
[[ 0.50420403  0.49579597]]
[[ 0.46247929  0.53752071]]
[[ 0.50417119  0.49582878]]
[[ 0.46449029  0.53550977]]
[[ 0.50423878  0.49576128]]
[[ 0.46652383  0.53347617]]
[[ 0.50434786  0.49565217]]
[[ 0.46864811  0.53135186]]
[[ 0.50459182  0.49540818]]
[[ 0.47100165  0.52899837]]
[[ 0.50506288  0.49493706]]
[[ 0.4736625  0.5263375]]
[[ 0.50568473  0.49431521]]
[[ 0.47665894  0.523341  ]]
[[ 0.50629896  0.49370101]]
[[ 0.4798159  0.5201841]]
[[ 0.50655097  0.49344903]]
[[ 0.48313111  0.51686889]]
[[ 0.50628847  0.49371144]]
[[ 0.48622     0.51378006]]
[[ 0.50557303  0.494427  ]]
[[ 0.48890674  0.51109332]]
[[ 0.5044269   0.49557316]]
[[ 0.49083406  0.50916594]]
[[ 0.50325286  0.49674714]]
[[ 0.49220535  0.50779468]]
[[ 0.5024026   0.49759743]]
[[ 0.49286497  0.50713503]]
[[ 0.501728  0.498272]]
[[ 0.4931587  0.5068413]]
[[ 0.50119811  0.49880192]]
[[ 0.49336401  0.50663602]]
[[ 0.50082755  0.49917242]]
[[ 0.49363583  0.50636411]]
[[

[[ 0.59815556  0.40184438]]
[[ 0.50203931  0.49796072]]
[[ 0.4003678  0.5996322]]
[[ 0.49575314  0.50424683]]
[[ 0.59833252  0.40166751]]
[[ 0.50285399  0.49714601]]
[[ 0.4016085   0.59839147]]
[[ 0.49695662  0.50304335]]
[[ 0.59911704  0.40088299]]
[[ 0.50444883  0.49555117]]
[[ 0.40374094  0.59625906]]
[[ 0.49904165  0.50095832]]
[[ 0.6007908  0.3992092]]
[[ 0.50704306  0.49295694]]
[[ 0.40702316  0.59297681]]
[[ 0.50226283  0.49773717]]
[[ 0.4018169   0.59818316]]
[[ 0.4964723   0.50352776]]
[[ 0.59608871  0.40391129]]
[[ 0.50391543  0.49608448]]
[[ 0.40405166  0.5959484 ]]
[[ 0.49871337  0.50128657]]
[[ 0.59803462  0.40196535]]
[[ 0.50683379  0.49316618]]
[[ 0.40773103  0.592269  ]]
[[ 0.50238425  0.49761581]]
[[ 0.40285122  0.59714872]]
[[ 0.49699146  0.50300848]]
[[ 0.59428251  0.40571743]]
[[ 0.50480056  0.49519941]]
[[ 0.40599898  0.59400105]]
[[ 0.5001694  0.4998306]]
[[ 0.40085638  0.59914362]]
[[ 0.49463794  0.50536197]]
[[ 0.59001207  0.40998784]]
[[ 0.50211847  0.49788147]

[[ 0.61331123  0.38668877]]
[[ 0.50440162  0.49559829]]
[[ 0.40329725  0.59670281]]
[[ 0.49514335  0.50485665]]
[[ 0.60760516  0.39239478]]
[[ 0.49873254  0.50126749]]
[[ 0.61194599  0.38805395]]
[[ 0.50319839  0.49680161]]
[[ 0.40208468  0.59791529]]
[[ 0.49365076  0.50634927]]
[[ 0.60543692  0.39456308]]
[[ 0.4968558  0.5031442]]
[[ 0.60926014  0.39073989]]
[[ 0.50082898  0.49917102]]
[[ 0.39963877  0.60036123]]
[[ 0.49084345  0.50915653]]
[[ 0.60155332  0.39844665]]
[[ 0.49346814  0.50653189]]
[[ 0.60465574  0.39534426]]
[[ 0.49679962  0.50320047]]
[[ 0.60857773  0.39142227]]
[[ 0.50084108  0.49915892]]
[[ 0.40007713  0.59992284]]
[[ 0.49097198  0.50902796]]
[[ 0.60112661  0.39887342]]
[[ 0.49364093  0.5063591 ]]
[[ 0.60423815  0.39576182]]
[[ 0.49697083  0.50302923]]
[[ 0.60813594  0.39186409]]
[[ 0.50099581  0.49900416]]
[[ 0.40058514  0.59941494]]
[[ 0.49113131  0.50886869]]
[[ 0.60067338  0.39932662]]
[[ 0.49374595  0.50625408]]
[[ 0.60369444  0.39630553]]
[[ 0.49697185  0.50302

[[ 0.50694031  0.49305975]]
[[ 0.49689442  0.50310564]]
[[ 0.51284158  0.48715839]]
[[ 0.50200951  0.49799046]]
[[ 0.49137279  0.50862724]]
[[ 0.50727963  0.49272043]]
[[ 0.49099201  0.50900799]]
[[ 0.51232207  0.48767793]]
[[ 0.48822904  0.5117709 ]]
[[ 0.51597595  0.48402405]]
[[ 0.4805705  0.5194295]]
[[ 0.51667064  0.48332939]]
[[ 0.46827337  0.53172666]]
[[ 0.5089224   0.49107754]]
[[ 0.45436829  0.54563177]]
[[ 0.49189633  0.50810367]]
[[ 0.54156643  0.45843354]]
[[ 0.47809601  0.52190393]]
[[ 0.53138202  0.46861804]]
[[ 0.4604052   0.53959477]]
[[ 0.51489282  0.48510718]]
[[ 0.43995836  0.56004161]]
[[ 0.49394313  0.50605685]]
[[ 0.54869175  0.45130825]]
[[ 0.47742218  0.52257788]]
[[ 0.53493834  0.46506166]]
[[ 0.45851496  0.54148501]]
[[ 0.51724178  0.48275822]]
[[ 0.43763971  0.56236035]]
[[ 0.49513659  0.50486344]]
[[ 0.54989988  0.45010009]]
[[ 0.47935209  0.52064794]]
[[ 0.5373317   0.46266827]]
[[ 0.46277416  0.5372259 ]]
[[ 0.52154398  0.47845608]]
[[ 0.44515786  0.55484

[[ 0.49822015  0.50177985]]
[[ 0.61575073  0.38424927]]
[[ 0.50506365  0.49493632]]
[[ 0.40214685  0.59785318]]
[[ 0.49712273  0.50287724]]
[[ 0.61425656  0.38574347]]
[[ 0.50358045  0.49641958]]
[[ 0.40068772  0.59931231]]
[[ 0.49523503  0.50476503]]
[[ 0.61177957  0.38822034]]
[[ 0.50111538  0.49888465]]
[[ 0.39831606  0.60168397]]
[[ 0.49241292  0.50758708]]
[[ 0.60798943  0.39201051]]
[[ 0.49747312  0.50252682]]
[[ 0.61443615  0.38556382]]
[[ 0.50388068  0.49611923]]
[[ 0.40177554  0.59822446]]
[[ 0.49575886  0.50424111]]
[[ 0.61208785  0.38791215]]
[[ 0.50150716  0.49849284]]
[[ 0.39938644  0.60061353]]
[[ 0.49291736  0.50708264]]
[[ 0.60819584  0.39180416]]
[[ 0.49784991  0.50215   ]]
[[ 0.61422801  0.38577196]]
[[ 0.50403029  0.49596968]]
[[ 0.40250245  0.59749752]]
[[ 0.49591556  0.50408447]]
[[ 0.61142045  0.38857955]]
[[ 0.5013659   0.49863401]]
[[ 0.39971963  0.60028034]]
[[ 0.49267638  0.50732362]]
[[ 0.60692096  0.3930791 ]]
[[ 0.49726295  0.50273699]]
[[ 0.61238521  0.387

[[ 0.61431193  0.38568798]]
[[ 0.50575364  0.49424636]]
[[ 0.40409508  0.59590495]]
[[ 0.50029838  0.49970162]]
[[ 0.39694309  0.60305685]]
[[ 0.49244669  0.50755334]]
[[ 0.60767841  0.39232162]]
[[ 0.49772489  0.50227511]]
[[ 0.61317009  0.38682997]]
[[ 0.50368446  0.49631548]]
[[ 0.39894137  0.6010586 ]]
[[ 0.49446443  0.5055356 ]]
[[ 0.60603029  0.39396974]]
[[ 0.49864966  0.50135034]]
[[ 0.61014611  0.38985398]]
[[ 0.50359803  0.49640194]]
[[ 0.39860409  0.60139591]]
[[ 0.49370921  0.50629079]]
[[ 0.60115665  0.39884332]]
[[ 0.49714166  0.5028584 ]]
[[ 0.60438055  0.39561945]]
[[ 0.50140703  0.49859294]]
[[ 0.39732659  0.60267341]]
[[ 0.49127784  0.50872219]]
[[ 0.5947451   0.40525487]]
[[ 0.49418071  0.50581926]]
[[ 0.59753919  0.40246081]]
[[ 0.49793655  0.50206339]]
[[ 0.60118455  0.39881548]]
[[ 0.50266862  0.49733138]]
[[ 0.40012714  0.59987283]]
[[ 0.49343619  0.50656384]]
[[ 0.59316593  0.40683407]]
[[ 0.49703231  0.50296772]]
[[ 0.59673399  0.40326601]]
[[ 0.501643  0.49835

[[ 0.47996339  0.52003658]]
[[ 0.51434165  0.48565829]]
[[ 0.48415083  0.51584923]]
[[ 0.51605773  0.4839423 ]]
[[ 0.48833588  0.51166409]]
[[ 0.51710951  0.48289058]]
[[ 0.49286616  0.5071339 ]]
[[ 0.51751971  0.48248029]]
[[ 0.49737316  0.50262684]]
[[ 0.51714981  0.48285019]]
[[ 0.50115865  0.49884132]]
[[ 0.48585376  0.51414621]]
[[ 0.60154605  0.39845401]]
[[ 0.49547607  0.50452393]]
[[ 0.60881937  0.39118066]]
[[ 0.50236142  0.49763852]]
[[ 0.39747968  0.60252035]]
[[ 0.49475786  0.50524223]]
[[ 0.60834926  0.39165074]]
[[ 0.50164175  0.49835825]]
[[ 0.39676693  0.6032331 ]]
[[ 0.49400964  0.50599033]]
[[ 0.6077832   0.39221674]]
[[ 0.50082427  0.4991757 ]]
[[ 0.39598015  0.60401988]]
[[ 0.49311179  0.50688815]]
[[ 0.60699785  0.39300221]]
[[ 0.49978039  0.50021964]]
[[ 0.61572278  0.38427725]]
[[ 0.5080716   0.49192831]]
[[ 0.40368792  0.59631205]]
[[ 0.5018183  0.4981817]]
[[ 0.3969723  0.6030277]]
[[ 0.49402043  0.5059796 ]]
[[ 0.6083588  0.3916412]]
[[ 0.50074995  0.49925005]

[[ 0.56467533  0.43532464]]
[[ 0.48482391  0.51517606]]
[[ 0.56219101  0.43780896]]
[[ 0.48295221  0.51704776]]
[[ 0.55934882  0.44065115]]
[[ 0.48070306  0.51929694]]
[[ 0.55623567  0.4437643 ]]
[[ 0.47803569  0.52196431]]
[[ 0.55269867  0.44730136]]
[[ 0.4749473   0.52505273]]
[[ 0.54864156  0.45135841]]
[[ 0.47126764  0.5287323 ]]
[[ 0.54401714  0.45598286]]
[[ 0.46691409  0.53308594]]
[[ 0.53860092  0.46139905]]
[[ 0.46191645  0.53808361]]
[[ 0.53233975  0.46766025]]
[[ 0.45614305  0.54385698]]
[[ 0.52517515  0.47482485]]
[[ 0.44935843  0.5506416 ]]
[[ 0.51700336  0.48299664]]
[[ 0.44143873  0.55856127]]
[[ 0.50750643  0.49249354]]
[[ 0.43245649  0.56754357]]
[[ 0.49660802  0.50339192]]
[[ 0.5530296   0.44697046]]
[[ 0.4942058   0.50579423]]
[[ 0.54714167  0.4528583 ]]
[[ 0.49207941  0.50792062]]
[[ 0.54131347  0.45868659]]
[[ 0.48991239  0.51008761]]
[[ 0.53529054  0.46470949]]
[[ 0.48754358  0.51245642]]
[[ 0.52926666  0.47073334]]
[[ 0.48536038  0.51463962]]
[[ 0.52334815  0.476

[[ 0.49675593  0.5032441 ]]
[[ 0.501625    0.49837494]]
[[ 0.49885777  0.5011422 ]]
[[ 0.50316346  0.49683651]]
[[ 0.50109309  0.49890691]]
[[ 0.49736887  0.50263113]]
[[ 0.50382113  0.4961789 ]]
[[ 0.50083572  0.49916422]]
[[ 0.49490049  0.50509948]]
[[ 0.50459313  0.49540684]]
[[ 0.49862117  0.50137883]]
[[ 0.50845724  0.49154276]]
[[ 0.50292242  0.49707755]]
[[ 0.49504879  0.5049513 ]]
[[ 0.50770539  0.49229461]]
[[ 0.49900857  0.5009914 ]]
[[ 0.51275182  0.48724824]]
[[ 0.50353462  0.49646538]]
[[ 0.49334863  0.50665134]]
[[ 0.50812399  0.49187595]]
[[ 0.49643973  0.50356025]]
[[ 0.51301271  0.48698735]]
[[ 0.49998569  0.50001436]]
[[ 0.51803827  0.4819617 ]]
[[ 0.50368792  0.49631205]]
[[ 0.48716637  0.5128336 ]]
[[ 0.50576031  0.49423972]]
[[ 0.47914329  0.52085668]]
[[ 0.50396836  0.49603161]]
[[ 0.46735376  0.53264624]]
[[ 0.49347311  0.50652683]]
[[ 0.53303576  0.46696422]]
[[ 0.48227799  0.51772201]]
[[ 0.52898014  0.47101992]]
[[ 0.46845704  0.53154296]]
[[ 0.51842576  0.481

[[ 0.59993452  0.40006554]]
[[ 0.5018099  0.4981901]]
[[ 0.40814528  0.59185475]]
[[ 0.49418259  0.50581735]]
[[ 0.59428722  0.40571278]]
[[ 0.49810013  0.50189984]]
[[ 0.5972693   0.40273064]]
[[ 0.50298017  0.49701977]]
[[ 0.41143873  0.5885613 ]]
[[ 0.49544978  0.50455022]]
[[ 0.59168333  0.40831664]]
[[ 0.49926549  0.50073451]]
[[ 0.59438062  0.40561935]]
[[ 0.50370049  0.49629951]]
[[ 0.41441703  0.58558303]]
[[ 0.49617669  0.50382328]]
[[ 0.58842707  0.41157296]]
[[ 0.49955425  0.50044578]]
[[ 0.59023106  0.40976894]]
[[ 0.50342286  0.49657714]]
[[ 0.416408    0.58359206]]
[[ 0.49576136  0.50423861]]
[[ 0.58332419  0.41667584]]
[[ 0.49848303  0.501517  ]]
[[ 0.58410436  0.41589561]]
[[ 0.5016526  0.4983474]]
[[ 0.41660249  0.58339757]]
[[ 0.49343526  0.50656474]]
[[ 0.576033  0.423967]]
[[ 0.49517232  0.50482768]]
[[ 0.57590079  0.42409915]]
[[ 0.49721301  0.50278699]]
[[ 0.57605404  0.42394602]]
[[ 0.49942213  0.50057787]]
[[ 0.57636011  0.42363989]]
[[ 0.50188649  0.49811348]]


[[ 0.5280534  0.4719466]]
[[ 0.47411725  0.52588278]]
[[ 0.52174002  0.47825995]]
[[ 0.47154617  0.52845389]]
[[ 0.51553196  0.48446804]]
[[ 0.470303    0.52969706]]
[[ 0.50934786  0.49065217]]
[[ 0.47142011  0.52857989]]
[[ 0.5034669   0.49653313]]
[[ 0.47233278  0.52766716]]
[[ 0.49791038  0.50208956]]
[[ 0.51093578  0.48906425]]
[[ 0.46123806  0.53876191]]
[[ 0.56902254  0.43097737]]
[[ 0.46221071  0.53778929]]
[[ 0.56997639  0.43002355]]
[[ 0.46282825  0.53717172]]
[[ 0.57037354  0.42962646]]
[[ 0.46308503  0.53691494]]
[[ 0.5698278   0.43017218]]
[[ 0.46302554  0.53697443]]
[[ 0.56901246  0.43098754]]
[[ 0.46268347  0.53731656]]
[[ 0.56796747  0.43203259]]
[[ 0.46220136  0.53779858]]
[[ 0.56667364  0.43332642]]
[[ 0.46152285  0.53847712]]
[[ 0.56523657  0.43476343]]
[[ 0.46062073  0.53937924]]
[[ 0.56359237  0.43640763]]
[[ 0.45949632  0.54050362]]
[[ 0.56178361  0.43821636]]
[[ 0.45818076  0.54181933]]
[[ 0.55973661  0.44026339]]
[[ 0.45664987  0.54335016]]
[[ 0.55749959  0.44250

[[ 0.49260628  0.50739378]]
[[ 0.50600034  0.49399972]]
[[ 0.49391422  0.50608581]]
[[ 0.5052368   0.49476317]]
[[ 0.49451804  0.5054819 ]]
[[ 0.50459158  0.49540845]]
[[ 0.49491104  0.50508898]]
[[ 0.50404423  0.49595568]]
[[ 0.49533117  0.50466889]]
[[ 0.50364715  0.49635282]]
[[ 0.49588135  0.50411868]]
[[ 0.50350004  0.4964999 ]]
[[ 0.49657533  0.5034247 ]]
[[ 0.50326848  0.49673155]]
[[ 0.49758008  0.50242001]]
[[ 0.50304115  0.49695879]]
[[ 0.49856204  0.5014379 ]]
[[ 0.50253558  0.49746439]]
[[ 0.49907413  0.5009259 ]]
[[ 0.50180584  0.49819413]]
[[ 0.49934748  0.50065255]]
[[ 0.50089514  0.49910486]]
[[ 0.49908891  0.50091112]]
[[ 0.49985504  0.50014496]]
[[ 0.46604651  0.53395349]]
[[ 0.57604295  0.42395711]]
[[ 0.46963674  0.53036332]]
[[ 0.58070266  0.41929731]]
[[ 0.47322157  0.5267784 ]]
[[ 0.58493102  0.41506895]]
[[ 0.47683829  0.52316171]]
[[ 0.58911872  0.41088131]]
[[ 0.48047468  0.51952541]]
[[ 0.59315503  0.40684506]]
[[ 0.48422787  0.51577216]]
[[ 0.59688705  0.403

[[ 0.56055993  0.43944007]]
[[ 0.45211533  0.5478847 ]]
[[ 0.55467826  0.44532171]]
[[ 0.44751424  0.55248576]]
[[ 0.54880804  0.45119193]]
[[ 0.44282222  0.55717772]]
[[ 0.54260033  0.45739967]]
[[ 0.43787661  0.56212342]]
[[ 0.53616405  0.46383592]]
[[ 0.43244597  0.567554  ]]
[[ 0.52929574  0.4707042 ]]
[[ 0.42652175  0.57347834]]
[[ 0.5220114   0.47798866]]
[[ 0.41994295  0.58005702]]
[[ 0.51398867  0.48601127]]
[[ 0.41267425  0.58732575]]
[[ 0.50525504  0.49474496]]
[[ 0.40441906  0.59558094]]
[[ 0.49568939  0.50431061]]
[[ 0.60397136  0.3960287 ]]
[[ 0.49899355  0.50100648]]
[[ 0.60705018  0.39294982]]
[[ 0.50366622  0.49633375]]
[[ 0.4057011   0.59429884]]
[[ 0.49585935  0.50414073]]
[[ 0.60156357  0.39843643]]
[[ 0.50037748  0.49962252]]
[[ 0.40404269  0.59595728]]
[[ 0.49267542  0.50732452]]
[[ 0.59572303  0.40427706]]
[[ 0.49676093  0.50323904]]
[[ 0.59956461  0.40043536]]
[[ 0.50192553  0.49807441]]
[[ 0.40846783  0.59153217]]
[[ 0.49485081  0.50514925]]
[[ 0.59492511  0.405

[[ 0.40639868  0.59360129]]
[[ 0.50070202  0.49929801]]
[[ 0.40191892  0.59808111]]
[[ 0.4956733   0.50432676]]
[[ 0.59090525  0.40909478]]
[[ 0.50379312  0.49620691]]
[[ 0.40570843  0.59429151]]
[[ 0.49973702  0.50026292]]
[[ 0.59484166  0.40515831]]
[[ 0.50900471  0.49099535]]
[[ 0.41186953  0.58813053]]
[[ 0.50614715  0.49385285]]
[[ 0.40891266  0.59108728]]
[[ 0.50265741  0.49734256]]
[[ 0.40522817  0.5947718 ]]
[[ 0.49846485  0.50153518]]
[[ 0.59058994  0.40941006]]
[[ 0.5074017  0.4925983]]
[[ 0.41089636  0.5891037 ]]
[[ 0.50447541  0.49552456]]
[[ 0.40791523  0.59208477]]
[[ 0.50093329  0.49906668]]
[[ 0.40435272  0.59564728]]
[[ 0.49681067  0.50318933]]
[[ 0.58611917  0.41388085]]
[[ 0.50545436  0.49454564]]
[[ 0.40970773  0.59029227]]
[[ 0.50255907  0.49744102]]
[[ 0.40692732  0.59307271]]
[[ 0.4990665   0.50093347]]
[[ 0.58685774  0.41314223]]
[[ 0.50838125  0.49161869]]
[[ 0.41387296  0.58612704]]
[[ 0.50630337  0.49369672]]
[[ 0.41206101  0.58793902]]
[[ 0.50374019  0.49625

[[ 0.49514848  0.50485152]]
[[ 0.59821916  0.40178087]]
[[ 0.49827254  0.50172746]]
[[ 0.60072649  0.39927354]]
[[ 0.50212985  0.49787018]]
[[ 0.39954942  0.60045058]]
[[ 0.49199653  0.50800353]]
[[ 0.59001118  0.40998876]]
[[ 0.49432948  0.50567055]]
[[ 0.59192675  0.40807328]]
[[ 0.4973909   0.50260913]]
[[ 0.59445614  0.40554383]]
[[ 0.50125045  0.49874949]]
[[ 0.40150461  0.59849536]]
[[ 0.49191874  0.5080812 ]]
[[ 0.58526152  0.41473845]]
[[ 0.49482995  0.50517005]]
[[ 0.58772969  0.41227031]]
[[ 0.49866694  0.501333  ]]
[[ 0.59103501  0.40896502]]
[[ 0.50342774  0.49657229]]
[[ 0.40739971  0.59260023]]
[[ 0.49565563  0.50434434]]
[[ 0.58443671  0.41556326]]
[[ 0.49996346  0.5000366 ]]
[[ 0.58796394  0.41203606]]
[[ 0.50530529  0.4946948 ]]
[[ 0.4125841   0.58741587]]
[[ 0.49862608  0.50137395]]
[[ 0.5823198   0.41768014]]
[[ 0.50383514  0.49616486]]
[[ 0.4136948   0.58630526]]
[[ 0.49726528  0.50273472]]
[[ 0.57674134  0.42325866]]
[[ 0.50223935  0.49776071]]
[[ 0.41581941  0.584

[[ 0.4969883   0.50301176]]
[[ 0.58797157  0.4120284 ]]
[[ 0.5014227   0.49857733]]
[[ 0.41504961  0.58495039]]
[[ 0.49468917  0.50531083]]
[[ 0.58146822  0.41853178]]
[[ 0.49818206  0.50181794]]
[[ 0.58253664  0.41746336]]
[[ 0.50228405  0.49771592]]
[[ 0.41919285  0.58080715]]
[[ 0.49555409  0.50444585]]
[[ 0.57593834  0.42406163]]
[[ 0.4985548   0.50144523]]
[[ 0.57641309  0.42358691]]
[[ 0.50200951  0.49799049]]
[[ 0.42232743  0.57767254]]
[[ 0.4949961   0.50500393]]
[[ 0.56925869  0.43074131]]
[[ 0.4971295  0.5028705]]
[[ 0.56844592  0.43155399]]
[[ 0.49973056  0.50026941]]
[[ 0.56721222  0.43278778]]
[[ 0.5026809  0.4973191]]
[[ 0.42801359  0.57198644]]
[[ 0.49565917  0.50434089]]
[[ 0.5594793   0.44052064]]
[[ 0.49724081  0.50275922]]
[[ 0.55698496  0.44301507]]
[[ 0.49891043  0.50108963]]
[[ 0.55396849  0.44603151]]
[[ 0.50056142  0.49943864]]
[[ 0.43364778  0.56635219]]
[[ 0.49311984  0.50688016]]
[[ 0.54555643  0.45444348]]
[[ 0.49325258  0.50674742]]
[[ 0.5413866   0.4586134

[[ 0.50701404  0.49298596]]
[[ 0.40224358  0.59775645]]
[[ 0.49934664  0.50065333]]
[[ 0.61379117  0.38620889]]
[[ 0.50625914  0.49374089]]
[[ 0.40140912  0.59859097]]
[[ 0.49832609  0.50167394]]
[[ 0.61213046  0.38786957]]
[[ 0.50492251  0.49507752]]
[[ 0.40001073  0.59998935]]
[[ 0.49677074  0.50322926]]
[[ 0.6098693   0.39013076]]
[[ 0.50295877  0.49704126]]
[[ 0.39799321  0.60200679]]
[[ 0.49461818  0.50538188]]
[[ 0.60692441  0.39307564]]
[[ 0.50026178  0.49973822]]
[[ 0.39524063  0.6047594 ]]
[[ 0.49169672  0.50830328]]
[[ 0.60309833  0.39690167]]
[[ 0.49675158  0.50324845]]
[[ 0.60996097  0.39003906]]
[[ 0.5033868   0.49661323]]
[[ 0.39860505  0.60139495]]
[[ 0.4955171   0.50448287]]
[[ 0.60797489  0.39202514]]
[[ 0.50170463  0.49829537]]
[[ 0.39690977  0.60309023]]
[[ 0.4936457   0.50635427]]
[[ 0.6053257   0.39467436]]
[[ 0.49934253  0.50065744]]
[[ 0.61285335  0.38714662]]
[[ 0.50677401  0.49322602]]
[[ 0.4022246   0.59777546]]
[[ 0.49954838  0.50045162]]
[[ 0.61251915  0.387

[[ 0.50658041  0.49341956]]
[[ 0.41781357  0.58218646]]
[[ 0.50483006  0.49516997]]
[[ 0.41692209  0.58307791]]
[[ 0.50279981  0.49720028]]
[[ 0.41577473  0.5842253 ]]
[[ 0.50054502  0.49945498]]
[[ 0.41433308  0.58566689]]
[[ 0.49814191  0.50185806]]
[[ 0.57359952  0.42640057]]
[[ 0.50681913  0.49318087]]
[[ 0.42289597  0.57710403]]
[[ 0.50583255  0.49416745]]
[[ 0.42308143  0.5769186 ]]
[[ 0.50465244  0.49534765]]
[[ 0.42317137  0.5768286 ]]
[[ 0.50334275  0.49665722]]
[[ 0.4230139   0.57698619]]
[[ 0.50192887  0.49807116]]
[[ 0.42261562  0.57738435]]
[[ 0.50029647  0.49970347]]
[[ 0.42202839  0.5779717 ]]
[[ 0.49848884  0.50151116]]
[[ 0.56723666  0.43276337]]
[[ 0.50703746  0.4929626 ]]
[[ 0.43141085  0.56858915]]
[[ 0.50686002  0.49313998]]
[[ 0.43272263  0.56727743]]
[[ 0.50667608  0.49332395]]
[[ 0.43403932  0.56596065]]
[[ 0.50657004  0.49343005]]
[[ 0.43534848  0.56465155]]
[[ 0.50651795  0.49348205]]
[[ 0.43662739  0.56337267]]
[[ 0.50656694  0.493433  ]]
[[ 0.43801403  0.561

[[ 0.50491029  0.49508965]]
[[ 0.4104349   0.58956516]]
[[ 0.49932119  0.50067872]]
[[ 0.58521575  0.41478428]]
[[ 0.50586957  0.49413046]]
[[ 0.41338471  0.58661526]]
[[ 0.50073224  0.49926779]]
[[ 0.4089354   0.59106463]]
[[ 0.49476475  0.50523525]]
[[ 0.57534111  0.42465886]]
[[ 0.50049245  0.49950749]]
[[ 0.41144302  0.588557  ]]
[[ 0.49524343  0.50475663]]
[[ 0.57307482  0.42692515]]
[[ 0.5014534  0.4985466]]
[[ 0.41529521  0.58470482]]
[[ 0.49712315  0.50287682]]
[[ 0.57203573  0.42796421]]
[[ 0.5038588  0.4961412]]
[[ 0.42093667  0.57906336]]
[[ 0.50034422  0.49965572]]
[[ 0.41915989  0.58084005]]
[[ 0.4963032  0.5036968]]
[[ 0.56646937  0.4335306 ]]
[[ 0.50286692  0.49713308]]
[[ 0.42546466  0.57453537]]
[[ 0.49976918  0.50023085]]
[[ 0.56753534  0.43246469]]
[[ 0.5069409   0.49305901]]
[[ 0.43406829  0.56593174]]
[[ 0.50508916  0.49491081]]
[[ 0.43467098  0.56532902]]
[[ 0.50304294  0.49695712]]
[[ 0.43501925  0.56498075]]
[[ 0.50083613  0.49916384]]
[[ 0.43511388  0.56488615]

[[ 0.49431241  0.50568759]]
[[ 0.57010317  0.42989683]]
[[ 0.49584553  0.50415444]]
[[ 0.56945252  0.43054748]]
[[ 0.49762705  0.50237292]]
[[ 0.56878859  0.43121135]]
[[ 0.49970472  0.50029522]]
[[ 0.56792957  0.43207043]]
[[ 0.50199318  0.49800682]]
[[ 0.42645779  0.57354218]]
[[ 0.49398315  0.50601685]]
[[ 0.55989844  0.44010156]]
[[ 0.49459675  0.50540328]]
[[ 0.5575847  0.4424153]]
[[ 0.49524251  0.50475746]]
[[ 0.55495435  0.44504559]]
[[ 0.49589658  0.50410342]]
[[ 0.55209035  0.44790968]]
[[ 0.49642879  0.50357115]]
[[ 0.54914886  0.45085111]]
[[ 0.49695438  0.50304562]]
[[ 0.54597044  0.45402959]]
[[ 0.49733415  0.50266582]]
[[ 0.54252321  0.45747679]]
[[ 0.4976283   0.50237173]]
[[ 0.53891432  0.46108562]]
[[ 0.49776804  0.50223196]]
[[ 0.53523058  0.46476942]]
[[ 0.49780372  0.50219625]]
[[ 0.53148144  0.46851847]]
[[ 0.49767187  0.50232816]]
[[ 0.5277673   0.47223273]]
[[ 0.49728474  0.50271523]]
[[ 0.52418572  0.47581431]]
[[ 0.49668378  0.50331628]]
[[ 0.52077329  0.47922

[[ 0.60809493  0.3919051 ]]
[[ 0.49924853  0.5007515 ]]
[[ 0.6144861   0.38551384]]
[[ 0.50551718  0.49448279]]
[[ 0.40051079  0.59948927]]
[[ 0.49682659  0.50317347]]
[[ 0.6110242   0.38897577]]
[[ 0.50253797  0.49746203]]
[[ 0.39735729  0.60264271]]
[[ 0.49333453  0.50666547]]
[[ 0.60628194  0.39371806]]
[[ 0.49817693  0.50182313]]
[[ 0.61262661  0.38737342]]
[[ 0.50443619  0.49556383]]
[[ 0.3993988  0.6006012]]
[[ 0.49573147  0.50426853]]
[[ 0.60911071  0.39088932]]
[[ 0.50133377  0.49866629]]
[[ 0.39620689  0.60379314]]
[[ 0.49227294  0.50772703]]
[[ 0.60438508  0.39561492]]
[[ 0.49700609  0.50299388]]
[[ 0.61070144  0.38929853]]
[[ 0.50322223  0.4967778 ]]
[[ 0.39826128  0.60173875]]
[[ 0.49467641  0.50532353]]
[[ 0.60724366  0.39275643]]
[[ 0.50017929  0.49982071]]
[[ 0.39513329  0.60486674]]
[[ 0.49132884  0.50867116]]
[[ 0.60263455  0.39736548]]
[[ 0.49605963  0.50394034]]
[[ 0.60899305  0.39100698]]
[[ 0.5022369   0.49776307]]
[[ 0.3973673   0.60263276]]
[[ 0.49393237  0.50606

[[ 0.52145416  0.47854587]]
[[ 0.44510269  0.55489731]]
[[ 0.49993411  0.50006586]]
[[ 0.56196636  0.4380337 ]]
[[ 0.4827131  0.5172869]]
[[ 0.54536438  0.45463571]]
[[ 0.46132025  0.53867972]]
[[ 0.52385426  0.47614577]]
[[ 0.43597901  0.56402099]]
[[ 0.49748507  0.50251496]]
[[ 0.56773478  0.43226525]]
[[ 0.47775117  0.52224886]]
[[ 0.54711872  0.45288122]]
[[ 0.45490083  0.54509914]]
[[ 0.52312505  0.47687501]]
[[ 0.42901766  0.5709824 ]]
[[ 0.4966616  0.5033384]]
[[ 0.57177353  0.42822647]]
[[ 0.47779265  0.52220738]]
[[ 0.55113029  0.44886974]]
[[ 0.45701924  0.54298073]]
[[ 0.5295139   0.47048607]]
[[ 0.4340221   0.56597787]]
[[ 0.50534105  0.49465898]]
[[ 0.4088853  0.5911147]]
[[ 0.47868788  0.52131218]]
[[ 0.55409467  0.44590533]]
[[ 0.46098199  0.53901803]]
[[ 0.53475249  0.46524754]]
[[ 0.44181052  0.55818951]]
[[ 0.5145998   0.48540014]]
[[ 0.42122358  0.57877642]]
[[ 0.49343398  0.50656599]]
[[ 0.56896758  0.43103239]]
[[ 0.481433    0.51856697]]
[[ 0.55516762  0.44483235]

[[ 0.61111826  0.38888174]]
[[ 0.50107342  0.49892664]]
[[ 0.39858571  0.60141432]]
[[ 0.49072731  0.50927269]]
[[ 0.60317153  0.39682844]]
[[ 0.49325645  0.50674355]]
[[ 0.60636157  0.3936384 ]]
[[ 0.49646446  0.50353545]]
[[ 0.61036915  0.38963085]]
[[ 0.50043976  0.49956024]]
[[ 0.39797911  0.60202086]]
[[ 0.49008888  0.50991106]]
[[ 0.60235381  0.39764619]]
[[ 0.49257329  0.50742668]]
[[ 0.60548687  0.39451313]]
[[ 0.49572438  0.50427562]]
[[ 0.60942692  0.39057308]]
[[ 0.49959961  0.50040036]]
[[ 0.61422914  0.38577083]]
[[ 0.50437665  0.49562335]]
[[ 0.40231532  0.59768468]]
[[ 0.49477479  0.50522524]]
[[ 0.60831279  0.39168721]]
[[ 0.49815363  0.50184631]]
[[ 0.61252576  0.38747427]]
[[ 0.50240153  0.49759847]]
[[ 0.399977    0.60002303]]
[[ 0.49225521  0.50774473]]
[[ 0.60518026  0.3948198 ]]
[[ 0.49505442  0.50494558]]
[[ 0.60870457  0.39129546]]
[[ 0.49856782  0.50143224]]
[[ 0.61308414  0.38691586]]
[[ 0.50297052  0.49702942]]
[[ 0.40061501  0.59938502]]
[[ 0.49297357  0.507

[[ 0.40313187  0.59686816]]
[[ 0.49560603  0.50439399]]
[[ 0.60921139  0.39078861]]
[[ 0.49939787  0.50060207]]
[[ 0.61381537  0.38618463]]
[[ 0.5041284   0.49587157]]
[[ 0.40224895  0.59775102]]
[[ 0.49456745  0.50543261]]
[[ 0.60778147  0.39221862]]
[[ 0.49801889  0.50198114]]
[[ 0.61197501  0.38802496]]
[[ 0.50236338  0.49763665]]
[[ 0.40032932  0.59967071]]
[[ 0.49243075  0.50756931]]
[[ 0.60494053  0.3950595 ]]
[[ 0.49543115  0.50456887]]
[[ 0.60861838  0.39138162]]
[[ 0.49920309  0.50079685]]
[[ 0.61317641  0.38682351]]
[[ 0.50385731  0.49614266]]
[[ 0.40217832  0.59782165]]
[[ 0.49429232  0.50570768]]
[[ 0.60704041  0.39295962]]
[[ 0.49766061  0.50233936]]
[[ 0.61111897  0.38888106]]
[[ 0.50183547  0.4981645 ]]
[[ 0.39996681  0.60003316]]
[[ 0.49183515  0.50816482]]
[[ 0.60375637  0.39624363]]
[[ 0.49464688  0.50535309]]
[[ 0.60720241  0.39279762]]
[[ 0.49817541  0.50182456]]
[[ 0.61150503  0.388495  ]]
[[ 0.50252354  0.49747646]]
[[ 0.40097165  0.59902841]]
[[ 0.49276045  0.507

[[ 0.60353708  0.39646289]]
[[ 0.4992294   0.50077057]]
[[ 0.61148047  0.38851956]]
[[ 0.50703108  0.49296892]]
[[ 0.4030681   0.59693182]]
[[ 0.50053382  0.49946627]]
[[ 0.39632279  0.60367721]]
[[ 0.49288943  0.5071106 ]]
[[ 0.60249227  0.3975077 ]]
[[ 0.49882099  0.5011791 ]]
[[ 0.61034834  0.38965172]]
[[ 0.50647515  0.49352488]]
[[ 0.40270522  0.59729475]]
[[ 0.50003457  0.49996543]]
[[ 0.39593107  0.60406893]]
[[ 0.49238729  0.50761271]]
[[ 0.60134017  0.39865983]]
[[ 0.49829909  0.50170088]]
[[ 0.60916799  0.39083204]]
[[ 0.50584936  0.49415064]]
[[ 0.40228158  0.59771836]]
[[ 0.49951434  0.5004856 ]]
[[ 0.61014485  0.38985512]]
[[ 0.50726789  0.49273208]]
[[ 0.40383825  0.59616178]]
[[ 0.50109851  0.49890149]]
[[ 0.39729908  0.60270089]]
[[ 0.49373117  0.50626886]]
[[ 0.6020174   0.39798257]]
[[ 0.49996901  0.50003105]]
[[ 0.61018139  0.38981855]]
[[ 0.50794154  0.49205846]]
[[ 0.40478572  0.59521431]]
[[ 0.50208437  0.49791566]]
[[ 0.3985571   0.60144287]]
[[ 0.49504593  0.504

[[ 0.49223244  0.50776756]]
[[ 0.58371121  0.41628879]]
[[ 0.49491388  0.50508606]]
[[ 0.58495367  0.41504627]]
[[ 0.49811116  0.50188881]]
[[ 0.586344    0.41365603]]
[[ 0.50179857  0.49820146]]
[[ 0.41585869  0.58414131]]
[[ 0.49403456  0.50596547]]
[[ 0.57916433  0.4208357 ]]
[[ 0.49639654  0.50360346]]
[[ 0.57957268  0.42042732]]
[[ 0.49913573  0.50086433]]
[[ 0.58048296  0.41951701]]
[[ 0.50226688  0.49773315]]
[[ 0.41955855  0.58044153]]
[[ 0.49419516  0.50580484]]
[[ 0.57297027  0.42702973]]
[[ 0.49571803  0.50428194]]
[[ 0.57255256  0.42744741]]
[[ 0.49736956  0.50263047]]
[[ 0.57221597  0.42778406]]
[[ 0.49928415  0.50071585]]
[[ 0.5718323   0.42816767]]
[[ 0.50148785  0.49851215]]
[[ 0.42368722  0.57631278]]
[[ 0.49308082  0.50691909]]
[[ 0.563519    0.43648097]]
[[ 0.49355868  0.50644141]]
[[ 0.56166041  0.43833956]]
[[ 0.49411955  0.50588042]]
[[ 0.55957192  0.44042799]]
[[ 0.49467245  0.50532752]]
[[ 0.55736035  0.44263962]]
[[ 0.49520642  0.50479364]]
[[ 0.55484438  0.445

[[ 0.50250101  0.49749905]]
[[ 0.39934766  0.60065228]]
[[ 0.49586576  0.50413424]]
[[ 0.60300791  0.39699209]]
[[ 0.50296998  0.49703005]]
[[ 0.39998522  0.60001475]]
[[ 0.49662837  0.5033716 ]]
[[ 0.60388631  0.39611366]]
[[ 0.50406617  0.49593386]]
[[ 0.40128767  0.59871227]]
[[ 0.49806389  0.50193608]]
[[ 0.60546339  0.39453661]]
[[ 0.50591522  0.49408475]]
[[ 0.40339848  0.59660149]]
[[ 0.5003435   0.49965653]]
[[ 0.39736792  0.60263211]]
[[ 0.49359715  0.50640279]]
[[ 0.59921634  0.40078363]]
[[ 0.50043857  0.49956134]]
[[ 0.39761275  0.60238725]]
[[ 0.49396774  0.50603223]]
[[ 0.59968185  0.40031812]]
[[ 0.50111067  0.49888927]]
[[ 0.39846337  0.60153663]]
[[ 0.49493709  0.50506288]]
[[ 0.60076988  0.39923012]]
[[ 0.50243467  0.49756533]]
[[ 0.40001795  0.59998214]]
[[ 0.43292636  0.56707364]]
[[ 0.53556061  0.46443939]]
[[ 0.43212616  0.56787384]]
[[ 0.53392798  0.46607202]]
[[ 0.4306325   0.56936753]]
[[ 0.53148484  0.46851516]]
[[ 0.42833185  0.57166821]]
[[ 0.52825677  0.471

[[ 0.49796703  0.502033  ]]
[[ 0.60074043  0.39925954]]
[[ 0.50122029  0.49877977]]
[[ 0.40471393  0.59528607]]
[[ 0.49099666  0.5090034 ]]
[[ 0.59193575  0.40806428]]
[[ 0.49244726  0.50755274]]
[[ 0.59297007  0.40702996]]
[[ 0.49427721  0.50572288]]
[[ 0.59443843  0.4055616 ]]
[[ 0.49650541  0.50349456]]
[[ 0.59637874  0.40362126]]
[[ 0.49915841  0.50084162]]
[[ 0.59880334  0.40119663]]
[[ 0.5022577  0.4977423]]
[[ 0.40705612  0.59294385]]
[[ 0.49191207  0.50808787]]
[[ 0.58976012  0.41023991]]
[[ 0.49308482  0.50691521]]
[[ 0.5904218   0.40957823]]
[[ 0.49453586  0.5054642 ]]
[[ 0.59136838  0.40863159]]
[[ 0.49627158  0.50372845]]
[[ 0.59264439  0.40735564]]
[[ 0.49823266  0.50176728]]
[[ 0.59426498  0.40573499]]
[[ 0.50046211  0.49953786]]
[[ 0.40668663  0.5933134 ]]
[[ 0.4898749  0.5101251]]
[[ 0.58365685  0.41634315]]
[[ 0.49002254  0.5099774 ]]
[[ 0.58314317  0.41685677]]
[[ 0.49027786  0.50972211]]
[[ 0.58277082  0.41722918]]
[[ 0.49063492  0.50936508]]
[[ 0.58250409  0.4174959

[[ 0.40618485  0.59381515]]
[[ 0.49938121  0.50061882]]
[[ 0.61132866  0.38867137]]
[[ 0.504776    0.49522394]]
[[ 0.40530184  0.59469807]]
[[ 0.49753079  0.5024693 ]]
[[ 0.60757476  0.39242524]]
[[ 0.50312412  0.49687579]]
[[ 0.40480313  0.59519696]]
[[ 0.49612117  0.50387883]]
[[ 0.60413921  0.39586076]]
[[ 0.50166547  0.4983345 ]]
[[ 0.40458012  0.59541994]]
[[ 0.49474666  0.50525331]]
[[ 0.60057408  0.39942592]]
[[ 0.50000352  0.49999648]]
[[ 0.4043012   0.59569883]]
[[ 0.49301046  0.5069896 ]]
[[ 0.5964883  0.4035117]]
[[ 0.49780723  0.5021928 ]]
[[ 0.60118479  0.39881524]]
[[ 0.50368667  0.49631333]]
[[ 0.41070724  0.58929282]]
[[ 0.49735704  0.50264299]]
[[ 0.59825343  0.40174657]]
[[ 0.5027107   0.49728927]]
[[ 0.41076434  0.5892356 ]]
[[ 0.49586201  0.50413805]]
[[ 0.59381574  0.40618429]]
[[ 0.5004335   0.49956653]]
[[ 0.4096114  0.5903886]]
[[ 0.49299538  0.50700462]]
[[ 0.58756566  0.41243431]]
[[ 0.49649027  0.50350964]]
[[ 0.58992529  0.41007471]]
[[ 0.50069612  0.4993039

[[ 0.40718067  0.59281939]]
[[ 0.49330989  0.50669008]]
[[ 0.59446204  0.40553796]]
[[ 0.49565175  0.50434828]]
[[ 0.5963937   0.40360633]]
[[ 0.49853548  0.50146455]]
[[ 0.5989213   0.40107864]]
[[ 0.50197911  0.49802092]]
[[ 0.40733078  0.59266919]]
[[ 0.4921695   0.50783056]]
[[ 0.59039122  0.40960875]]
[[ 0.49389222  0.50610781]]
[[ 0.59150922  0.40849078]]
[[ 0.49601218  0.50398779]]
[[ 0.59305435  0.40694562]]
[[ 0.4985109   0.50148904]]
[[ 0.59505111  0.40494889]]
[[ 0.50129586  0.49870408]]
[[ 0.40834925  0.59165078]]
[[ 0.49155277  0.50844723]]
[[ 0.58566225  0.41433769]]
[[ 0.49251264  0.5074873 ]]
[[ 0.58598107  0.41401893]]
[[ 0.49371436  0.50628561]]
[[ 0.58658814  0.41341189]]
[[ 0.49519521  0.50480479]]
[[ 0.58749449  0.41250554]]
[[ 0.49694344  0.50305659]]
[[ 0.58853525  0.41146481]]
[[ 0.49898222  0.50101781]]
[[ 0.58964688  0.41035315]]
[[ 0.5012694  0.4987306]]
[[ 0.41154021  0.58845979]]
[[ 0.49126452  0.50873554]]
[[ 0.5798682   0.42013183]]
[[ 0.49151236  0.50848

[[ 0.49729738  0.50270259]]
[[ 0.61359555  0.38640442]]
[[ 0.5024395   0.49756056]]
[[ 0.39947429  0.60052574]]
[[ 0.49296331  0.50703669]]
[[ 0.60789734  0.39210266]]
[[ 0.49682403  0.50317597]]
[[ 0.61293334  0.38706666]]
[[ 0.50173986  0.49826011]]
[[ 0.39865786  0.6013422 ]]
[[ 0.4920797   0.50792032]]
[[ 0.60671359  0.39328641]]
[[ 0.4956862   0.50431377]]
[[ 0.6114825   0.38851747]]
[[ 0.50028944  0.49971059]]
[[ 0.39713696  0.60286307]]
[[ 0.49043569  0.50956428]]
[[ 0.60457802  0.39542195]]
[[ 0.49372217  0.5062778 ]]
[[ 0.60895729  0.39104274]]
[[ 0.49789676  0.50210327]]
[[ 0.61432242  0.38567755]]
[[ 0.50316745  0.49683264]]
[[ 0.40024242  0.59975761]]
[[ 0.49377391  0.50622612]]
[[ 0.6089263  0.3910737]]
[[ 0.49779373  0.50220627]]
[[ 0.61411148  0.38588852]]
[[ 0.50290698  0.49709296]]
[[ 0.3998535   0.60014653]]
[[ 0.49335274  0.50664723]]
[[ 0.60833633  0.3916637 ]]
[[ 0.49719819  0.50280184]]
[[ 0.61334032  0.38665965]]
[[ 0.50211215  0.49788788]]
[[ 0.39897627  0.60102

[[ 0.58893067  0.41106936]]
[[ 0.50002378  0.49997622]]
[[ 0.4096418   0.59035814]]
[[ 0.48936448  0.5106355 ]]
[[ 0.57786554  0.42213449]]
[[ 0.48892674  0.51107329]]
[[ 0.57655495  0.42344505]]
[[ 0.48847702  0.51152295]]
[[ 0.57524455  0.42475551]]
[[ 0.48799565  0.51200432]]
[[ 0.57383579  0.42616415]]
[[ 0.48743096  0.51256901]]
[[ 0.57234514  0.42765486]]
[[ 0.48674077  0.51325929]]
[[ 0.57075924  0.42924073]]
[[ 0.48595467  0.51404524]]
[[ 0.5690003   0.43099973]]
[[ 0.48498031  0.51501966]]
[[ 0.56701905  0.4329809 ]]
[[ 0.48376068  0.51623929]]
[[ 0.5647493   0.43525073]]
[[ 0.48226437  0.5177356 ]]
[[ 0.5621959   0.43780413]]
[[ 0.48044947  0.5195505 ]]
[[ 0.55929512  0.44070491]]
[[ 0.47823408  0.52176601]]
[[ 0.55595309  0.44404691]]
[[ 0.47558811  0.52441192]]
[[ 0.5524236  0.4475764]]
[[ 0.47245517  0.52754486]]
[[ 0.5483067   0.45169336]]
[[ 0.46871197  0.53128803]]
[[ 0.54363918  0.45636079]]
[[ 0.46434537  0.5356546 ]]
[[ 0.53818744  0.46181253]]
[[ 0.45923615  0.54076

[[ 0.49708989  0.5029102 ]]
[[ 0.60586947  0.39413056]]
[[ 0.50067383  0.49932614]]
[[ 0.4012602  0.5987398]]
[[ 0.49056897  0.50943106]]
[[ 0.59739381  0.40260619]]
[[ 0.49256942  0.50743061]]
[[ 0.59954721  0.40045279]]
[[ 0.49510419  0.50489581]]
[[ 0.60238606  0.39761394]]
[[ 0.49820015  0.50179988]]
[[ 0.60592961  0.39407039]]
[[ 0.5018931   0.49810696]]
[[ 0.40327972  0.59672028]]
[[ 0.492053    0.50794697]]
[[ 0.59788615  0.40211391]]
[[ 0.49416462  0.50583535]]
[[ 0.60015303  0.399847  ]]
[[ 0.49677774  0.50322223]]
[[ 0.60309362  0.39690641]]
[[ 0.49992138  0.50007856]]
[[ 0.60671371  0.39328635]]
[[ 0.50369632  0.49630371]]
[[ 0.40580302  0.59419698]]
[[ 0.4939926   0.50600749]]
[[ 0.59890586  0.40109414]]
[[ 0.49614829  0.50385171]]
[[ 0.60125619  0.39874381]]
[[ 0.4988029   0.50119704]]
[[ 0.60424441  0.39575562]]
[[ 0.50200826  0.49799171]]
[[ 0.40416041  0.59583956]]
[[ 0.49172023  0.5082798 ]]
[[ 0.59504634  0.40495366]]
[[ 0.49317724  0.50682271]]
[[ 0.59648389  0.40351

[[ 0.50367469  0.49632534]]
[[ 0.41477305  0.58522695]]
[[ 0.49643478  0.50356513]]
[[ 0.58844161  0.41155836]]
[[ 0.50004113  0.49995884]]
[[ 0.41229269  0.58770728]]
[[ 0.49197924  0.50802076]]
[[ 0.58040297  0.41959703]]
[[ 0.4944191   0.50558096]]
[[ 0.58077699  0.41922301]]
[[ 0.49734166  0.50265831]]
[[ 0.5815919   0.41840816]]
[[ 0.50072092  0.49927899]]
[[ 0.41679749  0.58320248]]
[[ 0.49282187  0.50717807]]
[[ 0.57394588  0.42605406]]
[[ 0.4947848   0.50521517]]
[[ 0.57382119  0.42617875]]
[[ 0.49701822  0.50298184]]
[[ 0.5739091   0.42609084]]
[[ 0.49942872  0.50057131]]
[[ 0.57406431  0.42593572]]
[[ 0.50219208  0.49780798]]
[[ 0.42370304  0.57629699]]
[[ 0.49440882  0.50559115]]
[[ 0.56645232  0.43354768]]
[[ 0.49561605  0.50438392]]
[[ 0.56519878  0.43480119]]
[[ 0.49706349  0.50293648]]
[[ 0.56358671  0.43641332]]
[[ 0.49867389  0.50132614]]
[[ 0.56182849  0.43817148]]
[[ 0.50043273  0.49956724]]
[[ 0.42748642  0.57251358]]
[[ 0.49198449  0.50801551]]
[[ 0.55347639  0.446

[[ 0.48545262  0.51454735]]
[[ 0.55905575  0.44094425]]
[[ 0.38068038  0.61931968]]
[[ 0.47307304  0.52692693]]
[[ 0.58155179  0.41844824]]
[[ 0.47139838  0.52860159]]
[[ 0.58046544  0.4195345 ]]
[[ 0.47024006  0.52975994]]
[[ 0.57949024  0.42050973]]
[[ 0.46949747  0.53050256]]
[[ 0.57880044  0.42119959]]
[[ 0.46911591  0.53088409]]
[[ 0.57849032  0.42150974]]
[[ 0.469087    0.53091294]]
[[ 0.5785709  0.4214291]]
[[ 0.46944514  0.53055489]]
[[ 0.57902187  0.4209781 ]]
[[ 0.47010702  0.52989298]]
[[ 0.57983482  0.42016521]]
[[ 0.47107166  0.52892834]]
[[ 0.58101213  0.41898784]]
[[ 0.47231871  0.52768129]]
[[ 0.582569    0.41743103]]
[[ 0.4738982   0.52610171]]
[[ 0.58452803  0.41547197]]
[[ 0.47582704  0.52417302]]
[[ 0.58691728  0.41308275]]
[[ 0.47813201  0.52186805]]
[[ 0.58978105  0.41021895]]
[[ 0.48086414  0.51913589]]
[[ 0.59317482  0.40682521]]
[[ 0.48401865  0.51598144]]
[[ 0.59708911  0.4029108 ]]
[[ 0.48769924  0.51230073]]
[[ 0.601758    0.39824191]]
[[ 0.49200851  0.50799

[[ 0.506006    0.49399403]]
[[ 0.4630219   0.53697807]]
[[ 0.50687689  0.49312305]]
[[ 0.46578777  0.53421217]]
[[ 0.50793409  0.49206588]]
[[ 0.46855876  0.53144121]]
[[ 0.50913543  0.49086455]]
[[ 0.47155818  0.52844185]]
[[ 0.51039243  0.48960754]]
[[ 0.47487584  0.52512413]]
[[ 0.51176846  0.48823154]]
[[ 0.47852808  0.52147192]]
[[ 0.51337957  0.4866204 ]]
[[ 0.48242068  0.51757926]]
[[ 0.51490539  0.48509458]]
[[ 0.48637545  0.51362455]]
[[ 0.51572871  0.48427126]]
[[ 0.49046609  0.50953394]]
[[ 0.51578236  0.4842177 ]]
[[ 0.49448663  0.50551343]]
[[ 0.51512003  0.48487991]]
[[ 0.49787182  0.50212818]]
[[ 0.51410592  0.48589399]]
[[ 0.50015867  0.49984133]]
[[ 0.48901924  0.51098078]]
[[ 0.49795547  0.50204456]]
[[ 0.50911409  0.49088585]]
[[ 0.49860126  0.50139874]]
[[ 0.5086022   0.49139777]]
[[ 0.49937603  0.500624  ]]
[[ 0.50830519  0.49169481]]
[[ 0.5002628   0.49973723]]
[[ 0.49292907  0.5070709 ]]
[[ 0.49880558  0.50119448]]
[[ 0.50554228  0.49445766]]
[[ 0.50006813  0.499

[[ 0.49349818  0.50650185]]
[[ 0.50012702  0.49987307]]
[[ 0.4934288   0.50657123]]
[[ 0.49964523  0.50035477]]
[[ 0.50338203  0.496618  ]]
[[ 0.49949232  0.50050765]]
[[ 0.50238889  0.49761117]]
[[ 0.49938002  0.50062001]]
[[ 0.50188106  0.49811894]]
[[ 0.49942672  0.50057328]]
[[ 0.50182718  0.49817291]]
[[ 0.49986395  0.50013614]]
[[ 0.50211132  0.49788868]]
[[ 0.50074691  0.49925312]]
[[ 0.49948761  0.50051236]]
[[ 0.50248623  0.49751377]]
[[ 0.50170422  0.49829584]]
[[ 0.5009554   0.49904466]]
[[ 0.49959573  0.50040418]]
[[ 0.50493509  0.49506488]]
[[ 0.50395423  0.4960458 ]]
[[ 0.50188839  0.49811161]]
[[ 0.49713802  0.50286192]]
[[ 0.50831997  0.49168009]]
[[ 0.50364244  0.4963575 ]]
[[ 0.49655056  0.5034495 ]]
[[ 0.51112258  0.48887739]]
[[ 0.50333112  0.49666893]]
[[ 0.49358812  0.50641185]]
[[ 0.51146889  0.4885312 ]]
[[ 0.49908844  0.50091153]]
[[ 0.52020222  0.47979778]]
[[ 0.5063467  0.4936533]]
[[ 0.48915291  0.51084703]]
[[ 0.51270539  0.48729461]]
[[ 0.48191217  0.51808

[[ 0.5026806  0.4973194]]
[[ 0.40143722  0.59856278]]
[[ 0.49375638  0.50624359]]
[[ 0.60693961  0.39306045]]
[[ 0.49789029  0.50210971]]
[[ 0.6118384   0.38816157]]
[[ 0.50300312  0.49699691]]
[[ 0.40220305  0.59779698]]
[[ 0.49421546  0.50578457]]
[[ 0.60687965  0.39312035]]
[[ 0.49831274  0.50168729]]
[[ 0.61172819  0.38827181]]
[[ 0.50341976  0.4965803 ]]
[[ 0.40301976  0.59698021]]
[[ 0.49465311  0.50534689]]
[[ 0.60676312  0.39323694]]
[[ 0.49870667  0.5012933 ]]
[[ 0.61149633  0.3885037 ]]
[[ 0.50372869  0.49627128]]
[[ 0.40368307  0.59631687]]
[[ 0.49493173  0.50506824]]
[[ 0.60640424  0.39359578]]
[[ 0.49887326  0.50112665]]
[[ 0.61095095  0.38904911]]
[[ 0.50372243  0.49627757]]
[[ 0.40399411  0.59600586]]
[[ 0.49483505  0.50516492]]
[[ 0.60554045  0.39445946]]
[[ 0.49857661  0.50142342]]
[[ 0.60982013  0.39017981]]
[[ 0.50316077  0.49683926]]
[[ 0.40367824  0.59632176]]
[[ 0.49407098  0.50592899]]
[[ 0.60381907  0.39618099]]
[[ 0.49749896  0.50250101]]
[[ 0.60769975  0.39230

[[ 0.60424346  0.39575654]]
[[ 0.49505034  0.50494963]]
[[ 0.61239815  0.38760179]]
[[ 0.50291264  0.49708739]]
[[ 0.39873078  0.60126919]]
[[ 0.49584532  0.50415462]]
[[ 0.61193961  0.38806033]]
[[ 0.50306433  0.49693561]]
[[ 0.39854127  0.60145873]]
[[ 0.49534863  0.50465131]]
[[ 0.61028814  0.38971183]]
[[ 0.50194931  0.49805066]]
[[ 0.39716586  0.60283411]]
[[ 0.49365667  0.50634331]]
[[ 0.6074397  0.3925603]]
[[ 0.49953336  0.50046664]]
[[ 0.61480433  0.3851957 ]]
[[ 0.50682586  0.49317414]]
[[ 0.4021104   0.59788954]]
[[ 0.49917009  0.50082994]]
[[ 0.61361033  0.38638967]]
[[ 0.50609243  0.49390754]]
[[ 0.40126854  0.59873152]]
[[ 0.49811745  0.50188255]]
[[ 0.61174178  0.38825825]]
[[ 0.50463766  0.49536231]]
[[ 0.39973673  0.6002633 ]]
[[ 0.49641868  0.50358135]]
[[ 0.60916263  0.39083737]]
[[ 0.50242496  0.49757501]]
[[ 0.39746612  0.60253388]]
[[ 0.49400339  0.50599658]]
[[ 0.60578865  0.39421135]]
[[ 0.49939451  0.50060546]]
[[ 0.61290967  0.38709027]]
[[ 0.50644851  0.49355

[[ 0.51407373  0.48592627]]
[[ 0.47575897  0.52424103]]
[[ 0.50549763  0.49450237]]
[[ 0.47359884  0.52640116]]
[[ 0.4972586  0.5027414]]
[[ 0.50989437  0.49010563]]
[[ 0.49228364  0.50771642]]
[[ 0.50366515  0.49633482]]
[[ 0.49062899  0.50937098]]
[[ 0.49842709  0.50157291]]
[[ 0.50641602  0.49358401]]
[[ 0.49488145  0.50511855]]
[[ 0.502119    0.49788105]]
[[ 0.4926233   0.50737673]]
[[ 0.49891731  0.50108272]]
[[ 0.50363523  0.49636474]]
[[ 0.49667874  0.50332123]]
[[ 0.50089359  0.49910641]]
[[ 0.49517125  0.50482869]]
[[ 0.498712  0.501288]]
[[ 0.50026971  0.49973023]]
[[ 0.49678457  0.50321543]]
[[ 0.49823207  0.50176799]]
[[ 0.49854347  0.5014565 ]]
[[ 0.49782073  0.50217932]]
[[ 0.49664193  0.50335807]]
[[ 0.49456891  0.50543112]]
[[ 0.49181727  0.50818282]]
Average Score  185.48
Choice 1: 0.5024261375889584, Choice 0: 0.4975738624110416
